// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Notification.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationIntent int32

const (
	NotificationIntent_OPEN_APP        NotificationIntent = 0
	NotificationIntent_DO_NOTHING      NotificationIntent = 1
	NotificationIntent_OPEN_CONTAINER  NotificationIntent = 2
	NotificationIntent_OPEN_STORE_LINK NotificationIntent = 3
)

var NotificationIntent_name = map[int32]string{
	0: "OPEN_APP",
	1: "DO_NOTHING",
	2: "OPEN_CONTAINER",
	3: "OPEN_STORE_LINK",
}
var NotificationIntent_value = map[string]int32{
	"OPEN_APP":        0,
	"DO_NOTHING":      1,
	"OPEN_CONTAINER":  2,
	"OPEN_STORE_LINK": 3,
}

func (x NotificationIntent) String() string {
	return proto.EnumName(NotificationIntent_name, int32(x))
}
func (NotificationIntent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Notification_7b66cc59fa6e3e59, []int{0}
}

type Notification struct {
	AppId                string             `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SDesc                string             `protobuf:"bytes,3,opt,name=sDesc,proto3" json:"sDesc,omitempty"`
	Desc                 string             `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Intent               NotificationIntent `protobuf:"varint,5,opt,name=intent,proto3,enum=example.NotificationIntent" json:"intent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_Notification_7b66cc59fa6e3e59, []int{0}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetSDesc() string {
	if m != nil {
		return m.SDesc
	}
	return ""
}

func (m *Notification) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Notification) GetIntent() NotificationIntent {
	if m != nil {
		return m.Intent
	}
	return NotificationIntent_OPEN_APP
}

func init() {
	proto.RegisterType((*Notification)(nil), "example.Notification")
	proto.RegisterEnum("example.NotificationIntent", NotificationIntent_name, NotificationIntent_value)
}

func init() { proto.RegisterFile("Notification.proto", fileDescriptor_Notification_7b66cc59fa6e3e59) }

var fileDescriptor_Notification_7b66cc59fa6e3e59 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55, 0x9a, 0xc9, 0xc8, 0xc5, 0x83, 0x2c, 0x2f, 0x24,
	0xc2, 0xc5, 0x9a, 0x58, 0x50, 0xe0, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1,
	0x80, 0x44, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0x20, 0xa2, 0x60, 0x0e, 0x48, 0xb4, 0xd8,
	0x25, 0xb5, 0x38, 0x59, 0x82, 0x19, 0x22, 0x0a, 0xe6, 0x08, 0x09, 0x71, 0xb1, 0x80, 0x05, 0x59,
	0xc0, 0x82, 0x60, 0xb6, 0x90, 0x31, 0x17, 0x5b, 0x66, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x04, 0xab,
	0x02, 0xa3, 0x06, 0x9f, 0x91, 0xb4, 0x1e, 0xd4, 0x01, 0x7a, 0xc8, 0x96, 0x7b, 0x82, 0x95, 0x04,
	0x41, 0x95, 0x6a, 0x45, 0xa3, 0x3a, 0x1d, 0x22, 0x2b, 0xc4, 0xc3, 0xc5, 0xe1, 0x1f, 0xe0, 0xea,
	0x17, 0xef, 0x18, 0x10, 0x20, 0xc0, 0x20, 0xc4, 0xc7, 0xc5, 0xe5, 0xe2, 0x1f, 0xef, 0xe7, 0x1f,
	0xe2, 0xe1, 0xe9, 0xe7, 0x2e, 0xc0, 0x28, 0x24, 0xc4, 0xc5, 0x07, 0x96, 0x75, 0xf6, 0xf7, 0x0b,
	0x71, 0xf4, 0xf4, 0x73, 0x0d, 0x12, 0x60, 0x12, 0x12, 0xe6, 0xe2, 0x07, 0x8b, 0x05, 0x87, 0xf8,
	0x07, 0xb9, 0xc6, 0xfb, 0x78, 0xfa, 0x79, 0x0b, 0x30, 0x27, 0xb1, 0x81, 0x03, 0xc2, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x10, 0xea, 0x2c, 0x46, 0x1e, 0x01, 0x00, 0x00,
}
