// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Configurator.proto

package proxy.proto.models;

public final class ConfiguratorOuterClass {
  private ConfiguratorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proxy.proto.models.ActionIntent}
   */
  public enum ActionIntent
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLOSE_SOCKET = 0;</code>
     */
    CLOSE_SOCKET(0),
    /**
     * <pre>
     * Close sokcet and Reconecet after `T` seconds
     * </pre>
     *
     * <code>SNOOZE = 1;</code>
     */
    SNOOZE(1),
    /**
     * <pre>
     *Clear session and logout the user
     * </pre>
     *
     * <code>PURGE = 2;</code>
     */
    PURGE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLOSE_SOCKET = 0;</code>
     */
    public static final int CLOSE_SOCKET_VALUE = 0;
    /**
     * <pre>
     * Close sokcet and Reconecet after `T` seconds
     * </pre>
     *
     * <code>SNOOZE = 1;</code>
     */
    public static final int SNOOZE_VALUE = 1;
    /**
     * <pre>
     *Clear session and logout the user
     * </pre>
     *
     * <code>PURGE = 2;</code>
     */
    public static final int PURGE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionIntent valueOf(int value) {
      return forNumber(value);
    }

    public static ActionIntent forNumber(int value) {
      switch (value) {
        case 0: return CLOSE_SOCKET;
        case 1: return SNOOZE;
        case 2: return PURGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionIntent>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionIntent> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionIntent>() {
            public ActionIntent findValueByNumber(int number) {
              return ActionIntent.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proxy.proto.models.ConfiguratorOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionIntent[] VALUES = values();

    public static ActionIntent valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionIntent(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proxy.proto.models.ActionIntent)
  }

  public interface ConfiguratorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proxy.proto.models.Configurator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
     */
    int getIntentValue();
    /**
     * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
     */
    proxy.proto.models.ConfiguratorOuterClass.ActionIntent getIntent();

    /**
     * <code>string metaData = 2;</code>
     */
    java.lang.String getMetaData();
    /**
     * <code>string metaData = 2;</code>
     */
    com.google.protobuf.ByteString
        getMetaDataBytes();
  }
  /**
   * Protobuf type {@code proxy.proto.models.Configurator}
   */
  public  static final class Configurator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proxy.proto.models.Configurator)
      ConfiguratorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Configurator.newBuilder() to construct.
    private Configurator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Configurator() {
      intent_ = 0;
      metaData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Configurator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              intent_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              metaData_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.proto.models.ConfiguratorOuterClass.internal_static_proxy_proto_models_Configurator_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.proto.models.ConfiguratorOuterClass.internal_static_proxy_proto_models_Configurator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.proto.models.ConfiguratorOuterClass.Configurator.class, proxy.proto.models.ConfiguratorOuterClass.Configurator.Builder.class);
    }

    public static final int INTENT_FIELD_NUMBER = 1;
    private int intent_;
    /**
     * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
     */
    public int getIntentValue() {
      return intent_;
    }
    /**
     * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
     */
    public proxy.proto.models.ConfiguratorOuterClass.ActionIntent getIntent() {
      @SuppressWarnings("deprecation")
      proxy.proto.models.ConfiguratorOuterClass.ActionIntent result = proxy.proto.models.ConfiguratorOuterClass.ActionIntent.valueOf(intent_);
      return result == null ? proxy.proto.models.ConfiguratorOuterClass.ActionIntent.UNRECOGNIZED : result;
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object metaData_;
    /**
     * <code>string metaData = 2;</code>
     */
    public java.lang.String getMetaData() {
      java.lang.Object ref = metaData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metaData_ = s;
        return s;
      }
    }
    /**
     * <code>string metaData = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMetaDataBytes() {
      java.lang.Object ref = metaData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metaData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intent_ != proxy.proto.models.ConfiguratorOuterClass.ActionIntent.CLOSE_SOCKET.getNumber()) {
        output.writeEnum(1, intent_);
      }
      if (!getMetaDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metaData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intent_ != proxy.proto.models.ConfiguratorOuterClass.ActionIntent.CLOSE_SOCKET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, intent_);
      }
      if (!getMetaDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metaData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.proto.models.ConfiguratorOuterClass.Configurator)) {
        return super.equals(obj);
      }
      proxy.proto.models.ConfiguratorOuterClass.Configurator other = (proxy.proto.models.ConfiguratorOuterClass.Configurator) obj;

      boolean result = true;
      result = result && intent_ == other.intent_;
      result = result && getMetaData()
          .equals(other.getMetaData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTENT_FIELD_NUMBER;
      hash = (53 * hash) + intent_;
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetaData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.ConfiguratorOuterClass.Configurator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.proto.models.ConfiguratorOuterClass.Configurator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proxy.proto.models.Configurator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proxy.proto.models.Configurator)
        proxy.proto.models.ConfiguratorOuterClass.ConfiguratorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.proto.models.ConfiguratorOuterClass.internal_static_proxy_proto_models_Configurator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.proto.models.ConfiguratorOuterClass.internal_static_proxy_proto_models_Configurator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.proto.models.ConfiguratorOuterClass.Configurator.class, proxy.proto.models.ConfiguratorOuterClass.Configurator.Builder.class);
      }

      // Construct using proxy.proto.models.ConfiguratorOuterClass.Configurator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intent_ = 0;

        metaData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.proto.models.ConfiguratorOuterClass.internal_static_proxy_proto_models_Configurator_descriptor;
      }

      @java.lang.Override
      public proxy.proto.models.ConfiguratorOuterClass.Configurator getDefaultInstanceForType() {
        return proxy.proto.models.ConfiguratorOuterClass.Configurator.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.proto.models.ConfiguratorOuterClass.Configurator build() {
        proxy.proto.models.ConfiguratorOuterClass.Configurator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.proto.models.ConfiguratorOuterClass.Configurator buildPartial() {
        proxy.proto.models.ConfiguratorOuterClass.Configurator result = new proxy.proto.models.ConfiguratorOuterClass.Configurator(this);
        result.intent_ = intent_;
        result.metaData_ = metaData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.proto.models.ConfiguratorOuterClass.Configurator) {
          return mergeFrom((proxy.proto.models.ConfiguratorOuterClass.Configurator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.proto.models.ConfiguratorOuterClass.Configurator other) {
        if (other == proxy.proto.models.ConfiguratorOuterClass.Configurator.getDefaultInstance()) return this;
        if (other.intent_ != 0) {
          setIntentValue(other.getIntentValue());
        }
        if (!other.getMetaData().isEmpty()) {
          metaData_ = other.metaData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.proto.models.ConfiguratorOuterClass.Configurator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.proto.models.ConfiguratorOuterClass.Configurator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int intent_ = 0;
      /**
       * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
       */
      public int getIntentValue() {
        return intent_;
      }
      /**
       * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
       */
      public Builder setIntentValue(int value) {
        intent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
       */
      public proxy.proto.models.ConfiguratorOuterClass.ActionIntent getIntent() {
        @SuppressWarnings("deprecation")
        proxy.proto.models.ConfiguratorOuterClass.ActionIntent result = proxy.proto.models.ConfiguratorOuterClass.ActionIntent.valueOf(intent_);
        return result == null ? proxy.proto.models.ConfiguratorOuterClass.ActionIntent.UNRECOGNIZED : result;
      }
      /**
       * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
       */
      public Builder setIntent(proxy.proto.models.ConfiguratorOuterClass.ActionIntent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        intent_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.ActionIntent intent = 1;</code>
       */
      public Builder clearIntent() {
        
        intent_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object metaData_ = "";
      /**
       * <code>string metaData = 2;</code>
       */
      public java.lang.String getMetaData() {
        java.lang.Object ref = metaData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metaData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metaData = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMetaDataBytes() {
        java.lang.Object ref = metaData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metaData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metaData = 2;</code>
       */
      public Builder setMetaData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metaData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metaData = 2;</code>
       */
      public Builder clearMetaData() {
        
        metaData_ = getDefaultInstance().getMetaData();
        onChanged();
        return this;
      }
      /**
       * <code>string metaData = 2;</code>
       */
      public Builder setMetaDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metaData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proxy.proto.models.Configurator)
    }

    // @@protoc_insertion_point(class_scope:proxy.proto.models.Configurator)
    private static final proxy.proto.models.ConfiguratorOuterClass.Configurator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.proto.models.ConfiguratorOuterClass.Configurator();
    }

    public static proxy.proto.models.ConfiguratorOuterClass.Configurator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Configurator>
        PARSER = new com.google.protobuf.AbstractParser<Configurator>() {
      @java.lang.Override
      public Configurator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Configurator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Configurator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Configurator> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.proto.models.ConfiguratorOuterClass.Configurator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxy_proto_models_Configurator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxy_proto_models_Configurator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Configurator.proto\022\022proxy.proto.models" +
      "\"R\n\014Configurator\0220\n\006intent\030\001 \001(\0162 .proxy" +
      ".proto.models.ActionIntent\022\020\n\010metaData\030\002" +
      " \001(\t*7\n\014ActionIntent\022\020\n\014CLOSE_SOCKET\020\000\022\n" +
      "\n\006SNOOZE\020\001\022\t\n\005PURGE\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proxy_proto_models_Configurator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proxy_proto_models_Configurator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxy_proto_models_Configurator_descriptor,
        new java.lang.String[] { "Intent", "MetaData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
