// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameRequest.proto

package proxy.proto.models;

public final class GameRequestOuterClass {
  private GameRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proxy.proto.models.GameRequestType}
   */
  public enum GameRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *  Messages
     * </pre>
     *
     * <code>CREATE_ROOM_REQUEST = 0;</code>
     */
    CREATE_ROOM_REQUEST(0),
    /**
     * <code>JOIN_ROOM_REQUEST = 1;</code>
     */
    JOIN_ROOM_REQUEST(1),
    /**
     * <code>LEAVE_ROOM_REQUEST = 2;</code>
     */
    LEAVE_ROOM_REQUEST(2),
    /**
     * <code>DESTROY_ROOM_REQUEST = 3;</code>
     */
    DESTROY_ROOM_REQUEST(3),
    /**
     * <code>HALT_ROOM_REQUEST = 4;</code>
     */
    HALT_ROOM_REQUEST(4),
    /**
     * <code>GET_ROOMS_REQUEST = 5;</code>
     */
    GET_ROOMS_REQUEST(5),
    /**
     * <code>GET_ROOM_DETAILS_REQUEST = 6;</code>
     */
    GET_ROOM_DETAILS_REQUEST(6),
    /**
     * <code>KICK_PLAYER_FROM_ROOM_REQUEST = 7;</code>
     */
    KICK_PLAYER_FROM_ROOM_REQUEST(7),
    /**
     * <code>SEND_MESSAGE_REQUEST = 8;</code>
     */
    SEND_MESSAGE_REQUEST(8),
    /**
     * <code>GET_STATUS_REQUEST = 9;</code>
     */
    GET_STATUS_REQUEST(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *  Messages
     * </pre>
     *
     * <code>CREATE_ROOM_REQUEST = 0;</code>
     */
    public static final int CREATE_ROOM_REQUEST_VALUE = 0;
    /**
     * <code>JOIN_ROOM_REQUEST = 1;</code>
     */
    public static final int JOIN_ROOM_REQUEST_VALUE = 1;
    /**
     * <code>LEAVE_ROOM_REQUEST = 2;</code>
     */
    public static final int LEAVE_ROOM_REQUEST_VALUE = 2;
    /**
     * <code>DESTROY_ROOM_REQUEST = 3;</code>
     */
    public static final int DESTROY_ROOM_REQUEST_VALUE = 3;
    /**
     * <code>HALT_ROOM_REQUEST = 4;</code>
     */
    public static final int HALT_ROOM_REQUEST_VALUE = 4;
    /**
     * <code>GET_ROOMS_REQUEST = 5;</code>
     */
    public static final int GET_ROOMS_REQUEST_VALUE = 5;
    /**
     * <code>GET_ROOM_DETAILS_REQUEST = 6;</code>
     */
    public static final int GET_ROOM_DETAILS_REQUEST_VALUE = 6;
    /**
     * <code>KICK_PLAYER_FROM_ROOM_REQUEST = 7;</code>
     */
    public static final int KICK_PLAYER_FROM_ROOM_REQUEST_VALUE = 7;
    /**
     * <code>SEND_MESSAGE_REQUEST = 8;</code>
     */
    public static final int SEND_MESSAGE_REQUEST_VALUE = 8;
    /**
     * <code>GET_STATUS_REQUEST = 9;</code>
     */
    public static final int GET_STATUS_REQUEST_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameRequestType valueOf(int value) {
      return forNumber(value);
    }

    public static GameRequestType forNumber(int value) {
      switch (value) {
        case 0: return CREATE_ROOM_REQUEST;
        case 1: return JOIN_ROOM_REQUEST;
        case 2: return LEAVE_ROOM_REQUEST;
        case 3: return DESTROY_ROOM_REQUEST;
        case 4: return HALT_ROOM_REQUEST;
        case 5: return GET_ROOMS_REQUEST;
        case 6: return GET_ROOM_DETAILS_REQUEST;
        case 7: return KICK_PLAYER_FROM_ROOM_REQUEST;
        case 8: return SEND_MESSAGE_REQUEST;
        case 9: return GET_STATUS_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameRequestType>() {
            public GameRequestType findValueByNumber(int number) {
              return GameRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proxy.proto.models.GameRequestOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameRequestType[] VALUES = values();

    public static GameRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proxy.proto.models.GameRequestType)
  }

  public interface GameRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proxy.proto.models.GameRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
     */
    int getGameRequestTypeValue();
    /**
     * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
     */
    proxy.proto.models.GameRequestOuterClass.GameRequestType getGameRequestType();

    /**
     * <code>bytes messsage = 2;</code>
     */
    com.google.protobuf.ByteString getMesssage();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code proxy.proto.models.GameRequest}
   */
  public  static final class GameRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proxy.proto.models.GameRequest)
      GameRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameRequest.newBuilder() to construct.
    private GameRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameRequest() {
      gameRequestType_ = 0;
      messsage_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              gameRequestType_ = rawValue;
              break;
            }
            case 18: {

              messsage_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.proto.models.GameRequestOuterClass.internal_static_proxy_proto_models_GameRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.proto.models.GameRequestOuterClass.internal_static_proxy_proto_models_GameRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.proto.models.GameRequestOuterClass.GameRequest.class, proxy.proto.models.GameRequestOuterClass.GameRequest.Builder.class);
    }

    public static final int GAMEREQUESTTYPE_FIELD_NUMBER = 1;
    private int gameRequestType_;
    /**
     * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
     */
    public int getGameRequestTypeValue() {
      return gameRequestType_;
    }
    /**
     * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
     */
    public proxy.proto.models.GameRequestOuterClass.GameRequestType getGameRequestType() {
      @SuppressWarnings("deprecation")
      proxy.proto.models.GameRequestOuterClass.GameRequestType result = proxy.proto.models.GameRequestOuterClass.GameRequestType.valueOf(gameRequestType_);
      return result == null ? proxy.proto.models.GameRequestOuterClass.GameRequestType.UNRECOGNIZED : result;
    }

    public static final int MESSSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString messsage_;
    /**
     * <code>bytes messsage = 2;</code>
     */
    public com.google.protobuf.ByteString getMesssage() {
      return messsage_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gameRequestType_ != proxy.proto.models.GameRequestOuterClass.GameRequestType.CREATE_ROOM_REQUEST.getNumber()) {
        output.writeEnum(1, gameRequestType_);
      }
      if (!messsage_.isEmpty()) {
        output.writeBytes(2, messsage_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gameRequestType_ != proxy.proto.models.GameRequestOuterClass.GameRequestType.CREATE_ROOM_REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, gameRequestType_);
      }
      if (!messsage_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, messsage_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.proto.models.GameRequestOuterClass.GameRequest)) {
        return super.equals(obj);
      }
      proxy.proto.models.GameRequestOuterClass.GameRequest other = (proxy.proto.models.GameRequestOuterClass.GameRequest) obj;

      boolean result = true;
      result = result && gameRequestType_ == other.gameRequestType_;
      result = result && getMesssage()
          .equals(other.getMesssage());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GAMEREQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + gameRequestType_;
      hash = (37 * hash) + MESSSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMesssage().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameRequestOuterClass.GameRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.proto.models.GameRequestOuterClass.GameRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proxy.proto.models.GameRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proxy.proto.models.GameRequest)
        proxy.proto.models.GameRequestOuterClass.GameRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.proto.models.GameRequestOuterClass.internal_static_proxy_proto_models_GameRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.proto.models.GameRequestOuterClass.internal_static_proxy_proto_models_GameRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.proto.models.GameRequestOuterClass.GameRequest.class, proxy.proto.models.GameRequestOuterClass.GameRequest.Builder.class);
      }

      // Construct using proxy.proto.models.GameRequestOuterClass.GameRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        gameRequestType_ = 0;

        messsage_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.proto.models.GameRequestOuterClass.internal_static_proxy_proto_models_GameRequest_descriptor;
      }

      @java.lang.Override
      public proxy.proto.models.GameRequestOuterClass.GameRequest getDefaultInstanceForType() {
        return proxy.proto.models.GameRequestOuterClass.GameRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.proto.models.GameRequestOuterClass.GameRequest build() {
        proxy.proto.models.GameRequestOuterClass.GameRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.proto.models.GameRequestOuterClass.GameRequest buildPartial() {
        proxy.proto.models.GameRequestOuterClass.GameRequest result = new proxy.proto.models.GameRequestOuterClass.GameRequest(this);
        result.gameRequestType_ = gameRequestType_;
        result.messsage_ = messsage_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.proto.models.GameRequestOuterClass.GameRequest) {
          return mergeFrom((proxy.proto.models.GameRequestOuterClass.GameRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.proto.models.GameRequestOuterClass.GameRequest other) {
        if (other == proxy.proto.models.GameRequestOuterClass.GameRequest.getDefaultInstance()) return this;
        if (other.gameRequestType_ != 0) {
          setGameRequestTypeValue(other.getGameRequestTypeValue());
        }
        if (other.getMesssage() != com.google.protobuf.ByteString.EMPTY) {
          setMesssage(other.getMesssage());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.proto.models.GameRequestOuterClass.GameRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.proto.models.GameRequestOuterClass.GameRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int gameRequestType_ = 0;
      /**
       * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
       */
      public int getGameRequestTypeValue() {
        return gameRequestType_;
      }
      /**
       * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
       */
      public Builder setGameRequestTypeValue(int value) {
        gameRequestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
       */
      public proxy.proto.models.GameRequestOuterClass.GameRequestType getGameRequestType() {
        @SuppressWarnings("deprecation")
        proxy.proto.models.GameRequestOuterClass.GameRequestType result = proxy.proto.models.GameRequestOuterClass.GameRequestType.valueOf(gameRequestType_);
        return result == null ? proxy.proto.models.GameRequestOuterClass.GameRequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
       */
      public Builder setGameRequestType(proxy.proto.models.GameRequestOuterClass.GameRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gameRequestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.GameRequestType gameRequestType = 1;</code>
       */
      public Builder clearGameRequestType() {
        
        gameRequestType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messsage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes messsage = 2;</code>
       */
      public com.google.protobuf.ByteString getMesssage() {
        return messsage_;
      }
      /**
       * <code>bytes messsage = 2;</code>
       */
      public Builder setMesssage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes messsage = 2;</code>
       */
      public Builder clearMesssage() {
        
        messsage_ = getDefaultInstance().getMesssage();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proxy.proto.models.GameRequest)
    }

    // @@protoc_insertion_point(class_scope:proxy.proto.models.GameRequest)
    private static final proxy.proto.models.GameRequestOuterClass.GameRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.proto.models.GameRequestOuterClass.GameRequest();
    }

    public static proxy.proto.models.GameRequestOuterClass.GameRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameRequest>
        PARSER = new com.google.protobuf.AbstractParser<GameRequest>() {
      @java.lang.Override
      public GameRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.proto.models.GameRequestOuterClass.GameRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxy_proto_models_GameRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxy_proto_models_GameRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GameRequest.proto\022\022proxy.proto.models\"" +
      "k\n\013GameRequest\022<\n\017gameRequestType\030\001 \001(\0162" +
      "#.proxy.proto.models.GameRequestType\022\020\n\010" +
      "messsage\030\002 \001(\014\022\014\n\004name\030\003 \001(\t*\224\002\n\017GameReq" +
      "uestType\022\027\n\023CREATE_ROOM_REQUEST\020\000\022\025\n\021JOI" +
      "N_ROOM_REQUEST\020\001\022\026\n\022LEAVE_ROOM_REQUEST\020\002" +
      "\022\030\n\024DESTROY_ROOM_REQUEST\020\003\022\025\n\021HALT_ROOM_" +
      "REQUEST\020\004\022\025\n\021GET_ROOMS_REQUEST\020\005\022\034\n\030GET_" +
      "ROOM_DETAILS_REQUEST\020\006\022!\n\035KICK_PLAYER_FR" +
      "OM_ROOM_REQUEST\020\007\022\030\n\024SEND_MESSAGE_REQUES" +
      "T\020\010\022\026\n\022GET_STATUS_REQUEST\020\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proxy_proto_models_GameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proxy_proto_models_GameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxy_proto_models_GameRequest_descriptor,
        new java.lang.String[] { "GameRequestType", "Messsage", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
