// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameEvents.proto

package proxy.proto.models;

public final class GameEvents {
  private GameEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proxy.proto.models.GameEventType}
   */
  public enum GameEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ROOM_CREATED_EVENT = 0;</code>
     */
    ROOM_CREATED_EVENT(0),
    /**
     * <code>ROOM_JOINED_EVENT = 1;</code>
     */
    ROOM_JOINED_EVENT(1),
    /**
     * <code>ROOM_LEFT_EVENT = 2;</code>
     */
    ROOM_LEFT_EVENT(2),
    /**
     * <code>ROOM_DESTROYED_EVENT = 3;</code>
     */
    ROOM_DESTROYED_EVENT(3),
    /**
     * <code>ROOM_FULL_EVENT = 4;</code>
     */
    ROOM_FULL_EVENT(4),
    /**
     * <code>GAME_PAUSED_EVENT = 5;</code>
     */
    GAME_PAUSED_EVENT(5),
    /**
     * <code>GAME_RESUMED_EVENT = 6;</code>
     */
    GAME_RESUMED_EVENT(6),
    /**
     * <code>GAME_CREATED_EVENT = 7;</code>
     */
    GAME_CREATED_EVENT(7),
    /**
     * <code>GAME_DESTROYED_EVENT = 8;</code>
     */
    GAME_DESTROYED_EVENT(8),
    /**
     * <code>GAME_FINISHED_EVENT = 9;</code>
     */
    GAME_FINISHED_EVENT(9),
    /**
     * <code>GAME_STOPPED_EVENT = 10;</code>
     */
    GAME_STOPPED_EVENT(10),
    /**
     * <code>GAME_MESSAGE_EVENT = 11;</code>
     */
    GAME_MESSAGE_EVENT(11),
    /**
     * <code>SOCKET_SERVER_PING = 12;</code>
     */
    SOCKET_SERVER_PING(12),
    /**
     * <code>SOCKET_SERVER_PONG = 13;</code>
     */
    SOCKET_SERVER_PONG(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ROOM_CREATED_EVENT = 0;</code>
     */
    public static final int ROOM_CREATED_EVENT_VALUE = 0;
    /**
     * <code>ROOM_JOINED_EVENT = 1;</code>
     */
    public static final int ROOM_JOINED_EVENT_VALUE = 1;
    /**
     * <code>ROOM_LEFT_EVENT = 2;</code>
     */
    public static final int ROOM_LEFT_EVENT_VALUE = 2;
    /**
     * <code>ROOM_DESTROYED_EVENT = 3;</code>
     */
    public static final int ROOM_DESTROYED_EVENT_VALUE = 3;
    /**
     * <code>ROOM_FULL_EVENT = 4;</code>
     */
    public static final int ROOM_FULL_EVENT_VALUE = 4;
    /**
     * <code>GAME_PAUSED_EVENT = 5;</code>
     */
    public static final int GAME_PAUSED_EVENT_VALUE = 5;
    /**
     * <code>GAME_RESUMED_EVENT = 6;</code>
     */
    public static final int GAME_RESUMED_EVENT_VALUE = 6;
    /**
     * <code>GAME_CREATED_EVENT = 7;</code>
     */
    public static final int GAME_CREATED_EVENT_VALUE = 7;
    /**
     * <code>GAME_DESTROYED_EVENT = 8;</code>
     */
    public static final int GAME_DESTROYED_EVENT_VALUE = 8;
    /**
     * <code>GAME_FINISHED_EVENT = 9;</code>
     */
    public static final int GAME_FINISHED_EVENT_VALUE = 9;
    /**
     * <code>GAME_STOPPED_EVENT = 10;</code>
     */
    public static final int GAME_STOPPED_EVENT_VALUE = 10;
    /**
     * <code>GAME_MESSAGE_EVENT = 11;</code>
     */
    public static final int GAME_MESSAGE_EVENT_VALUE = 11;
    /**
     * <code>SOCKET_SERVER_PING = 12;</code>
     */
    public static final int SOCKET_SERVER_PING_VALUE = 12;
    /**
     * <code>SOCKET_SERVER_PONG = 13;</code>
     */
    public static final int SOCKET_SERVER_PONG_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameEventType valueOf(int value) {
      return forNumber(value);
    }

    public static GameEventType forNumber(int value) {
      switch (value) {
        case 0: return ROOM_CREATED_EVENT;
        case 1: return ROOM_JOINED_EVENT;
        case 2: return ROOM_LEFT_EVENT;
        case 3: return ROOM_DESTROYED_EVENT;
        case 4: return ROOM_FULL_EVENT;
        case 5: return GAME_PAUSED_EVENT;
        case 6: return GAME_RESUMED_EVENT;
        case 7: return GAME_CREATED_EVENT;
        case 8: return GAME_DESTROYED_EVENT;
        case 9: return GAME_FINISHED_EVENT;
        case 10: return GAME_STOPPED_EVENT;
        case 11: return GAME_MESSAGE_EVENT;
        case 12: return SOCKET_SERVER_PING;
        case 13: return SOCKET_SERVER_PONG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameEventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameEventType>() {
            public GameEventType findValueByNumber(int number) {
              return GameEventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proxy.proto.models.GameEvents.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameEventType[] VALUES = values();

    public static GameEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameEventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proxy.proto.models.GameEventType)
  }

  public interface GameEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proxy.proto.models.GameEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
     */
    int getGameEventTypeValue();
    /**
     * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
     */
    proxy.proto.models.GameEvents.GameEventType getGameEventType();

    /**
     * <code>bytes messsage = 3;</code>
     */
    com.google.protobuf.ByteString getMesssage();

    /**
     * <code>string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code proxy.proto.models.GameEvent}
   */
  public  static final class GameEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proxy.proto.models.GameEvent)
      GameEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameEvent.newBuilder() to construct.
    private GameEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameEvent() {
      gameEventType_ = 0;
      messsage_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              gameEventType_ = rawValue;
              break;
            }
            case 26: {

              messsage_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.proto.models.GameEvents.internal_static_proxy_proto_models_GameEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.proto.models.GameEvents.internal_static_proxy_proto_models_GameEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.proto.models.GameEvents.GameEvent.class, proxy.proto.models.GameEvents.GameEvent.Builder.class);
    }

    public static final int GAMEEVENTTYPE_FIELD_NUMBER = 1;
    private int gameEventType_;
    /**
     * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
     */
    public int getGameEventTypeValue() {
      return gameEventType_;
    }
    /**
     * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
     */
    public proxy.proto.models.GameEvents.GameEventType getGameEventType() {
      @SuppressWarnings("deprecation")
      proxy.proto.models.GameEvents.GameEventType result = proxy.proto.models.GameEvents.GameEventType.valueOf(gameEventType_);
      return result == null ? proxy.proto.models.GameEvents.GameEventType.UNRECOGNIZED : result;
    }

    public static final int MESSSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messsage_;
    /**
     * <code>bytes messsage = 3;</code>
     */
    public com.google.protobuf.ByteString getMesssage() {
      return messsage_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gameEventType_ != proxy.proto.models.GameEvents.GameEventType.ROOM_CREATED_EVENT.getNumber()) {
        output.writeEnum(1, gameEventType_);
      }
      if (!messsage_.isEmpty()) {
        output.writeBytes(3, messsage_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gameEventType_ != proxy.proto.models.GameEvents.GameEventType.ROOM_CREATED_EVENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, gameEventType_);
      }
      if (!messsage_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messsage_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.proto.models.GameEvents.GameEvent)) {
        return super.equals(obj);
      }
      proxy.proto.models.GameEvents.GameEvent other = (proxy.proto.models.GameEvents.GameEvent) obj;

      boolean result = true;
      result = result && gameEventType_ == other.gameEventType_;
      result = result && getMesssage()
          .equals(other.getMesssage());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GAMEEVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + gameEventType_;
      hash = (37 * hash) + MESSSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMesssage().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.GameEvents.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.proto.models.GameEvents.GameEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proxy.proto.models.GameEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proxy.proto.models.GameEvent)
        proxy.proto.models.GameEvents.GameEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.proto.models.GameEvents.internal_static_proxy_proto_models_GameEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.proto.models.GameEvents.internal_static_proxy_proto_models_GameEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.proto.models.GameEvents.GameEvent.class, proxy.proto.models.GameEvents.GameEvent.Builder.class);
      }

      // Construct using proxy.proto.models.GameEvents.GameEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        gameEventType_ = 0;

        messsage_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.proto.models.GameEvents.internal_static_proxy_proto_models_GameEvent_descriptor;
      }

      @java.lang.Override
      public proxy.proto.models.GameEvents.GameEvent getDefaultInstanceForType() {
        return proxy.proto.models.GameEvents.GameEvent.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.proto.models.GameEvents.GameEvent build() {
        proxy.proto.models.GameEvents.GameEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.proto.models.GameEvents.GameEvent buildPartial() {
        proxy.proto.models.GameEvents.GameEvent result = new proxy.proto.models.GameEvents.GameEvent(this);
        result.gameEventType_ = gameEventType_;
        result.messsage_ = messsage_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.proto.models.GameEvents.GameEvent) {
          return mergeFrom((proxy.proto.models.GameEvents.GameEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.proto.models.GameEvents.GameEvent other) {
        if (other == proxy.proto.models.GameEvents.GameEvent.getDefaultInstance()) return this;
        if (other.gameEventType_ != 0) {
          setGameEventTypeValue(other.getGameEventTypeValue());
        }
        if (other.getMesssage() != com.google.protobuf.ByteString.EMPTY) {
          setMesssage(other.getMesssage());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.proto.models.GameEvents.GameEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.proto.models.GameEvents.GameEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int gameEventType_ = 0;
      /**
       * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
       */
      public int getGameEventTypeValue() {
        return gameEventType_;
      }
      /**
       * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
       */
      public Builder setGameEventTypeValue(int value) {
        gameEventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
       */
      public proxy.proto.models.GameEvents.GameEventType getGameEventType() {
        @SuppressWarnings("deprecation")
        proxy.proto.models.GameEvents.GameEventType result = proxy.proto.models.GameEvents.GameEventType.valueOf(gameEventType_);
        return result == null ? proxy.proto.models.GameEvents.GameEventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
       */
      public Builder setGameEventType(proxy.proto.models.GameEvents.GameEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gameEventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.GameEventType gameEventType = 1;</code>
       */
      public Builder clearGameEventType() {
        
        gameEventType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messsage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes messsage = 3;</code>
       */
      public com.google.protobuf.ByteString getMesssage() {
        return messsage_;
      }
      /**
       * <code>bytes messsage = 3;</code>
       */
      public Builder setMesssage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes messsage = 3;</code>
       */
      public Builder clearMesssage() {
        
        messsage_ = getDefaultInstance().getMesssage();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proxy.proto.models.GameEvent)
    }

    // @@protoc_insertion_point(class_scope:proxy.proto.models.GameEvent)
    private static final proxy.proto.models.GameEvents.GameEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.proto.models.GameEvents.GameEvent();
    }

    public static proxy.proto.models.GameEvents.GameEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameEvent>
        PARSER = new com.google.protobuf.AbstractParser<GameEvent>() {
      @java.lang.Override
      public GameEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.proto.models.GameEvents.GameEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxy_proto_models_GameEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxy_proto_models_GameEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GameEvents.proto\022\022proxy.proto.models\"e" +
      "\n\tGameEvent\0228\n\rgameEventType\030\001 \001(\0162!.pro" +
      "xy.proto.models.GameEventType\022\020\n\010messsag" +
      "e\030\003 \001(\014\022\014\n\004name\030\004 \001(\t*\334\002\n\rGameEventType\022" +
      "\026\n\022ROOM_CREATED_EVENT\020\000\022\025\n\021ROOM_JOINED_E" +
      "VENT\020\001\022\023\n\017ROOM_LEFT_EVENT\020\002\022\030\n\024ROOM_DEST" +
      "ROYED_EVENT\020\003\022\023\n\017ROOM_FULL_EVENT\020\004\022\025\n\021GA" +
      "ME_PAUSED_EVENT\020\005\022\026\n\022GAME_RESUMED_EVENT\020" +
      "\006\022\026\n\022GAME_CREATED_EVENT\020\007\022\030\n\024GAME_DESTRO" +
      "YED_EVENT\020\010\022\027\n\023GAME_FINISHED_EVENT\020\t\022\026\n\022" +
      "GAME_STOPPED_EVENT\020\n\022\026\n\022GAME_MESSAGE_EVE" +
      "NT\020\013\022\026\n\022SOCKET_SERVER_PING\020\014\022\026\n\022SOCKET_S" +
      "ERVER_PONG\020\rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proxy_proto_models_GameEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proxy_proto_models_GameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxy_proto_models_GameEvent_descriptor,
        new java.lang.String[] { "GameEventType", "Messsage", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
