// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package proxy.proto.models;

public final class NotificationOuterClass {
  private NotificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proxy.proto.models.NotificationIntent}
   */
  public enum NotificationIntent
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OPEN_APP = 0;</code>
     */
    OPEN_APP(0),
    /**
     * <code>DO_NOTHING = 1;</code>
     */
    DO_NOTHING(1),
    /**
     * <code>OPEN_CONTAINER = 2;</code>
     */
    OPEN_CONTAINER(2),
    /**
     * <code>OPEN_STORE_LINK = 3;</code>
     */
    OPEN_STORE_LINK(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OPEN_APP = 0;</code>
     */
    public static final int OPEN_APP_VALUE = 0;
    /**
     * <code>DO_NOTHING = 1;</code>
     */
    public static final int DO_NOTHING_VALUE = 1;
    /**
     * <code>OPEN_CONTAINER = 2;</code>
     */
    public static final int OPEN_CONTAINER_VALUE = 2;
    /**
     * <code>OPEN_STORE_LINK = 3;</code>
     */
    public static final int OPEN_STORE_LINK_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NotificationIntent valueOf(int value) {
      return forNumber(value);
    }

    public static NotificationIntent forNumber(int value) {
      switch (value) {
        case 0: return OPEN_APP;
        case 1: return DO_NOTHING;
        case 2: return OPEN_CONTAINER;
        case 3: return OPEN_STORE_LINK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NotificationIntent>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NotificationIntent> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NotificationIntent>() {
            public NotificationIntent findValueByNumber(int number) {
              return NotificationIntent.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proxy.proto.models.NotificationOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final NotificationIntent[] VALUES = values();

    public static NotificationIntent valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NotificationIntent(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proxy.proto.models.NotificationIntent)
  }

  public interface NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proxy.proto.models.Notification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appId = 1;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string appId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string sDesc = 3;</code>
     */
    java.lang.String getSDesc();
    /**
     * <code>string sDesc = 3;</code>
     */
    com.google.protobuf.ByteString
        getSDescBytes();

    /**
     * <code>string Desc = 4;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string Desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
     */
    int getIntentValue();
    /**
     * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
     */
    proxy.proto.models.NotificationOuterClass.NotificationIntent getIntent();

    /**
     * <pre>
     * If true, show the notification if app_id is present in DB, else show it anyways
     * </pre>
     *
     * <code>bool showIfInstalled = 6;</code>
     */
    boolean getShowIfInstalled();
  }
  /**
   * Protobuf type {@code proxy.proto.models.Notification}
   */
  public  static final class Notification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proxy.proto.models.Notification)
      NotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notification.newBuilder() to construct.
    private Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notification() {
      appId_ = "";
      title_ = "";
      sDesc_ = "";
      desc_ = "";
      intent_ = 0;
      showIfInstalled_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sDesc_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              intent_ = rawValue;
              break;
            }
            case 48: {

              showIfInstalled_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.proto.models.NotificationOuterClass.internal_static_proxy_proto_models_Notification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.proto.models.NotificationOuterClass.internal_static_proxy_proto_models_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.proto.models.NotificationOuterClass.Notification.class, proxy.proto.models.NotificationOuterClass.Notification.Builder.class);
    }

    public static final int APPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appId_;
    /**
     * <code>string appId = 1;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string appId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object sDesc_;
    /**
     * <code>string sDesc = 3;</code>
     */
    public java.lang.String getSDesc() {
      java.lang.Object ref = sDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string sDesc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSDescBytes() {
      java.lang.Object ref = sDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object desc_;
    /**
     * <code>string Desc = 4;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string Desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTENT_FIELD_NUMBER = 5;
    private int intent_;
    /**
     * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
     */
    public int getIntentValue() {
      return intent_;
    }
    /**
     * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
     */
    public proxy.proto.models.NotificationOuterClass.NotificationIntent getIntent() {
      @SuppressWarnings("deprecation")
      proxy.proto.models.NotificationOuterClass.NotificationIntent result = proxy.proto.models.NotificationOuterClass.NotificationIntent.valueOf(intent_);
      return result == null ? proxy.proto.models.NotificationOuterClass.NotificationIntent.UNRECOGNIZED : result;
    }

    public static final int SHOWIFINSTALLED_FIELD_NUMBER = 6;
    private boolean showIfInstalled_;
    /**
     * <pre>
     * If true, show the notification if app_id is present in DB, else show it anyways
     * </pre>
     *
     * <code>bool showIfInstalled = 6;</code>
     */
    public boolean getShowIfInstalled() {
      return showIfInstalled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getSDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sDesc_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      if (intent_ != proxy.proto.models.NotificationOuterClass.NotificationIntent.OPEN_APP.getNumber()) {
        output.writeEnum(5, intent_);
      }
      if (showIfInstalled_ != false) {
        output.writeBool(6, showIfInstalled_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getSDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sDesc_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      if (intent_ != proxy.proto.models.NotificationOuterClass.NotificationIntent.OPEN_APP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, intent_);
      }
      if (showIfInstalled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, showIfInstalled_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.proto.models.NotificationOuterClass.Notification)) {
        return super.equals(obj);
      }
      proxy.proto.models.NotificationOuterClass.Notification other = (proxy.proto.models.NotificationOuterClass.Notification) obj;

      boolean result = true;
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getSDesc()
          .equals(other.getSDesc());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && intent_ == other.intent_;
      result = result && (getShowIfInstalled()
          == other.getShowIfInstalled());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + SDESC_FIELD_NUMBER;
      hash = (53 * hash) + getSDesc().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + INTENT_FIELD_NUMBER;
      hash = (53 * hash) + intent_;
      hash = (37 * hash) + SHOWIFINSTALLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getShowIfInstalled());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.proto.models.NotificationOuterClass.Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.proto.models.NotificationOuterClass.Notification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proxy.proto.models.Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proxy.proto.models.Notification)
        proxy.proto.models.NotificationOuterClass.NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.proto.models.NotificationOuterClass.internal_static_proxy_proto_models_Notification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.proto.models.NotificationOuterClass.internal_static_proxy_proto_models_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.proto.models.NotificationOuterClass.Notification.class, proxy.proto.models.NotificationOuterClass.Notification.Builder.class);
      }

      // Construct using proxy.proto.models.NotificationOuterClass.Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appId_ = "";

        title_ = "";

        sDesc_ = "";

        desc_ = "";

        intent_ = 0;

        showIfInstalled_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.proto.models.NotificationOuterClass.internal_static_proxy_proto_models_Notification_descriptor;
      }

      @java.lang.Override
      public proxy.proto.models.NotificationOuterClass.Notification getDefaultInstanceForType() {
        return proxy.proto.models.NotificationOuterClass.Notification.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.proto.models.NotificationOuterClass.Notification build() {
        proxy.proto.models.NotificationOuterClass.Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.proto.models.NotificationOuterClass.Notification buildPartial() {
        proxy.proto.models.NotificationOuterClass.Notification result = new proxy.proto.models.NotificationOuterClass.Notification(this);
        result.appId_ = appId_;
        result.title_ = title_;
        result.sDesc_ = sDesc_;
        result.desc_ = desc_;
        result.intent_ = intent_;
        result.showIfInstalled_ = showIfInstalled_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.proto.models.NotificationOuterClass.Notification) {
          return mergeFrom((proxy.proto.models.NotificationOuterClass.Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.proto.models.NotificationOuterClass.Notification other) {
        if (other == proxy.proto.models.NotificationOuterClass.Notification.getDefaultInstance()) return this;
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getSDesc().isEmpty()) {
          sDesc_ = other.sDesc_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.intent_ != 0) {
          setIntentValue(other.getIntentValue());
        }
        if (other.getShowIfInstalled() != false) {
          setShowIfInstalled(other.getShowIfInstalled());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.proto.models.NotificationOuterClass.Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.proto.models.NotificationOuterClass.Notification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string appId = 1;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sDesc_ = "";
      /**
       * <code>string sDesc = 3;</code>
       */
      public java.lang.String getSDesc() {
        java.lang.Object ref = sDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sDesc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSDescBytes() {
        java.lang.Object ref = sDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sDesc = 3;</code>
       */
      public Builder setSDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sDesc = 3;</code>
       */
      public Builder clearSDesc() {
        
        sDesc_ = getDefaultInstance().getSDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string sDesc = 3;</code>
       */
      public Builder setSDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sDesc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string Desc = 4;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Desc = 4;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Desc = 4;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string Desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private int intent_ = 0;
      /**
       * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
       */
      public int getIntentValue() {
        return intent_;
      }
      /**
       * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
       */
      public Builder setIntentValue(int value) {
        intent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
       */
      public proxy.proto.models.NotificationOuterClass.NotificationIntent getIntent() {
        @SuppressWarnings("deprecation")
        proxy.proto.models.NotificationOuterClass.NotificationIntent result = proxy.proto.models.NotificationOuterClass.NotificationIntent.valueOf(intent_);
        return result == null ? proxy.proto.models.NotificationOuterClass.NotificationIntent.UNRECOGNIZED : result;
      }
      /**
       * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
       */
      public Builder setIntent(proxy.proto.models.NotificationOuterClass.NotificationIntent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        intent_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proxy.proto.models.NotificationIntent intent = 5;</code>
       */
      public Builder clearIntent() {
        
        intent_ = 0;
        onChanged();
        return this;
      }

      private boolean showIfInstalled_ ;
      /**
       * <pre>
       * If true, show the notification if app_id is present in DB, else show it anyways
       * </pre>
       *
       * <code>bool showIfInstalled = 6;</code>
       */
      public boolean getShowIfInstalled() {
        return showIfInstalled_;
      }
      /**
       * <pre>
       * If true, show the notification if app_id is present in DB, else show it anyways
       * </pre>
       *
       * <code>bool showIfInstalled = 6;</code>
       */
      public Builder setShowIfInstalled(boolean value) {
        
        showIfInstalled_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If true, show the notification if app_id is present in DB, else show it anyways
       * </pre>
       *
       * <code>bool showIfInstalled = 6;</code>
       */
      public Builder clearShowIfInstalled() {
        
        showIfInstalled_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proxy.proto.models.Notification)
    }

    // @@protoc_insertion_point(class_scope:proxy.proto.models.Notification)
    private static final proxy.proto.models.NotificationOuterClass.Notification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.proto.models.NotificationOuterClass.Notification();
    }

    public static proxy.proto.models.NotificationOuterClass.Notification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Notification>
        PARSER = new com.google.protobuf.AbstractParser<Notification>() {
      @java.lang.Override
      public Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Notification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.proto.models.NotificationOuterClass.Notification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proxy_proto_models_Notification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proxy_proto_models_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\022\022proxy.proto.models" +
      "\"\232\001\n\014Notification\022\r\n\005appId\030\001 \001(\t\022\r\n\005titl" +
      "e\030\002 \001(\t\022\r\n\005sDesc\030\003 \001(\t\022\014\n\004Desc\030\004 \001(\t\0226\n\006" +
      "intent\030\005 \001(\0162&.proxy.proto.models.Notifi" +
      "cationIntent\022\027\n\017showIfInstalled\030\006 \001(\010*[\n" +
      "\022NotificationIntent\022\014\n\010OPEN_APP\020\000\022\016\n\nDO_" +
      "NOTHING\020\001\022\022\n\016OPEN_CONTAINER\020\002\022\023\n\017OPEN_ST" +
      "ORE_LINK\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proxy_proto_models_Notification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proxy_proto_models_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proxy_proto_models_Notification_descriptor,
        new java.lang.String[] { "AppId", "Title", "SDesc", "Desc", "Intent", "ShowIfInstalled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
