// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameEvents.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proxy.Proto.Models {

  /// <summary>Holder for reflection information generated from GameEvents.proto</summary>
  public static partial class GameEventsReflection {

    #region Descriptor
    /// <summary>File descriptor for GameEvents.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameEventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBHYW1lRXZlbnRzLnByb3RvEhJwcm94eS5wcm90by5tb2RlbHMiVwoJR2Ft",
            "ZUV2ZW50EjgKDWdhbWVFdmVudFR5cGUYASABKA4yIS5wcm94eS5wcm90by5t",
            "b2RlbHMuR2FtZUV2ZW50VHlwZRIQCghtZXNzc2FnZRgDIAEoDCqsAgoNR2Ft",
            "ZUV2ZW50VHlwZRIWChJST09NX0NSRUFURURfRVZFTlQQABIVChFST09NX0pP",
            "SU5FRF9FVkVOVBABEhMKD1JPT01fTEVGVF9FVkVOVBACEhgKFFJPT01fREVT",
            "VFJPWUVEX0VWRU5UEAMSEwoPUk9PTV9GVUxMX0VWRU5UEAQSFQoRR0FNRV9Q",
            "QVVTRURfRVZFTlQQBRIWChJHQU1FX1JFU1VNRURfRVZFTlQQBhIWChJHQU1F",
            "X0NSRUFURURfRVZFTlQQBxIYChRHQU1FX0RFU1RST1lFRF9FVkVOVBAIEhcK",
            "E0dBTUVfRklOSVNIRURfRVZFTlQQCRIWChJHQU1FX1NUT1BQRURfRVZFTlQQ",
            "ChIWChJHQU1FX01FU1NBR0VfRVZFTlQQC2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proxy.Proto.Models.GameEventType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proxy.Proto.Models.GameEvent), global::Proxy.Proto.Models.GameEvent.Parser, new[]{ "GameEventType", "Messsage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameEventType {
    [pbr::OriginalName("ROOM_CREATED_EVENT")] RoomCreatedEvent = 0,
    [pbr::OriginalName("ROOM_JOINED_EVENT")] RoomJoinedEvent = 1,
    [pbr::OriginalName("ROOM_LEFT_EVENT")] RoomLeftEvent = 2,
    [pbr::OriginalName("ROOM_DESTROYED_EVENT")] RoomDestroyedEvent = 3,
    [pbr::OriginalName("ROOM_FULL_EVENT")] RoomFullEvent = 4,
    [pbr::OriginalName("GAME_PAUSED_EVENT")] GamePausedEvent = 5,
    [pbr::OriginalName("GAME_RESUMED_EVENT")] GameResumedEvent = 6,
    [pbr::OriginalName("GAME_CREATED_EVENT")] GameCreatedEvent = 7,
    [pbr::OriginalName("GAME_DESTROYED_EVENT")] GameDestroyedEvent = 8,
    [pbr::OriginalName("GAME_FINISHED_EVENT")] GameFinishedEvent = 9,
    [pbr::OriginalName("GAME_STOPPED_EVENT")] GameStoppedEvent = 10,
    [pbr::OriginalName("GAME_MESSAGE_EVENT")] GameMessageEvent = 11,
  }

  #endregion

  #region Messages
  public sealed partial class GameEvent : pb::IMessage<GameEvent> {
    private static readonly pb::MessageParser<GameEvent> _parser = new pb::MessageParser<GameEvent>(() => new GameEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proxy.Proto.Models.GameEventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent(GameEvent other) : this() {
      gameEventType_ = other.gameEventType_;
      messsage_ = other.messsage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent Clone() {
      return new GameEvent(this);
    }

    /// <summary>Field number for the "gameEventType" field.</summary>
    public const int GameEventTypeFieldNumber = 1;
    private global::Proxy.Proto.Models.GameEventType gameEventType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proxy.Proto.Models.GameEventType GameEventType {
      get { return gameEventType_; }
      set {
        gameEventType_ = value;
      }
    }

    /// <summary>Field number for the "messsage" field.</summary>
    public const int MesssageFieldNumber = 3;
    private pb::ByteString messsage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Messsage {
      get { return messsage_; }
      set {
        messsage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameEventType != other.GameEventType) return false;
      if (Messsage != other.Messsage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GameEventType != 0) hash ^= GameEventType.GetHashCode();
      if (Messsage.Length != 0) hash ^= Messsage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GameEventType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GameEventType);
      }
      if (Messsage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Messsage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GameEventType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GameEventType);
      }
      if (Messsage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Messsage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameEvent other) {
      if (other == null) {
        return;
      }
      if (other.GameEventType != 0) {
        GameEventType = other.GameEventType;
      }
      if (other.Messsage.Length != 0) {
        Messsage = other.Messsage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            gameEventType_ = (global::Proxy.Proto.Models.GameEventType) input.ReadEnum();
            break;
          }
          case 26: {
            Messsage = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
