// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proxy.Proto.Models {

  /// <summary>Holder for reflection information generated from GameResponse.proto</summary>
  public static partial class GameResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for GameResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJHYW1lUmVzcG9uc2UucHJvdG8SEnByb3h5LnByb3RvLm1vZGVscyJxCgxH",
            "YW1lUmVzcG9uc2USPgoQZ2FtZVJlc3BvbnNlVHlwZRgBIAEoDjIkLnByb3h5",
            "LnByb3RvLm1vZGVscy5HYW1lUmVzcG9uc2VUeXBlEg8KB3N1Y2Nlc3MYAiAB",
            "KAgSEAoIbWVzc3NhZ2UYAyABKAwqnwIKEEdhbWVSZXNwb25zZVR5cGUSGAoU",
            "Q1JFQVRFX1JPT01fUkVTUE9OU0UQABIWChJKT0lOX1JPT01fUkVTUE9OU0UQ",
            "ARIXChNMRUFWRV9ST09NX1JFU1BPTlNFEAISGQoVREVTVFJPWV9ST09NX1JF",
            "U1BPTlNFEAMSFgoSSEFMVF9ST09NX1JFU1BPTlNFEAQSFgoSR0VUX1JPT01T",
            "X1JFU1BPTlNFEAUSHQoZR0VUX1JPT01fREVUQUlMU19SRVNQT05TRRAGEiIK",
            "HktJQ0tfUExBWUVSX0ZST01fUk9PTV9SRVNQT05TRRAHEhkKFVNFTkRfTUVT",
            "U0FHRV9SRVNQT05TRRAIEhcKE0dFVF9TVEFUVVNfUkVTUE9OU0UQCWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proxy.Proto.Models.GameResponseType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proxy.Proto.Models.GameResponse), global::Proxy.Proto.Models.GameResponse.Parser, new[]{ "GameResponseType", "Success", "Messsage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameResponseType {
    [pbr::OriginalName("CREATE_ROOM_RESPONSE")] CreateRoomResponse = 0,
    [pbr::OriginalName("JOIN_ROOM_RESPONSE")] JoinRoomResponse = 1,
    [pbr::OriginalName("LEAVE_ROOM_RESPONSE")] LeaveRoomResponse = 2,
    [pbr::OriginalName("DESTROY_ROOM_RESPONSE")] DestroyRoomResponse = 3,
    [pbr::OriginalName("HALT_ROOM_RESPONSE")] HaltRoomResponse = 4,
    [pbr::OriginalName("GET_ROOMS_RESPONSE")] GetRoomsResponse = 5,
    [pbr::OriginalName("GET_ROOM_DETAILS_RESPONSE")] GetRoomDetailsResponse = 6,
    [pbr::OriginalName("KICK_PLAYER_FROM_ROOM_RESPONSE")] KickPlayerFromRoomResponse = 7,
    [pbr::OriginalName("SEND_MESSAGE_RESPONSE")] SendMessageResponse = 8,
    [pbr::OriginalName("GET_STATUS_RESPONSE")] GetStatusResponse = 9,
  }

  #endregion

  #region Messages
  public sealed partial class GameResponse : pb::IMessage<GameResponse> {
    private static readonly pb::MessageParser<GameResponse> _parser = new pb::MessageParser<GameResponse>(() => new GameResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proxy.Proto.Models.GameResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResponse(GameResponse other) : this() {
      gameResponseType_ = other.gameResponseType_;
      success_ = other.success_;
      messsage_ = other.messsage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResponse Clone() {
      return new GameResponse(this);
    }

    /// <summary>Field number for the "gameResponseType" field.</summary>
    public const int GameResponseTypeFieldNumber = 1;
    private global::Proxy.Proto.Models.GameResponseType gameResponseType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proxy.Proto.Models.GameResponseType GameResponseType {
      get { return gameResponseType_; }
      set {
        gameResponseType_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 2;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "messsage" field.</summary>
    public const int MesssageFieldNumber = 3;
    private pb::ByteString messsage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Messsage {
      get { return messsage_; }
      set {
        messsage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameResponseType != other.GameResponseType) return false;
      if (Success != other.Success) return false;
      if (Messsage != other.Messsage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GameResponseType != 0) hash ^= GameResponseType.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (Messsage.Length != 0) hash ^= Messsage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GameResponseType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GameResponseType);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Messsage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Messsage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GameResponseType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GameResponseType);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (Messsage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Messsage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameResponse other) {
      if (other == null) {
        return;
      }
      if (other.GameResponseType != 0) {
        GameResponseType = other.GameResponseType;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Messsage.Length != 0) {
        Messsage = other.Messsage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            gameResponseType_ = (global::Proxy.Proto.Models.GameResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Messsage = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
