// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proxy.Proto.Models {

  /// <summary>Holder for reflection information generated from GameRequest.proto</summary>
  public static partial class GameRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for GameRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHYW1lUmVxdWVzdC5wcm90bxIScHJveHkucHJvdG8ubW9kZWxzImsKC0dh",
            "bWVSZXF1ZXN0EjwKD2dhbWVSZXF1ZXN0VHlwZRgBIAEoDjIjLnByb3h5LnBy",
            "b3RvLm1vZGVscy5HYW1lUmVxdWVzdFR5cGUSEAoIbWVzc3NhZ2UYAiABKAwS",
            "DAoEbmFtZRgDIAEoCSqUAgoPR2FtZVJlcXVlc3RUeXBlEhcKE0NSRUFURV9S",
            "T09NX1JFUVVFU1QQABIVChFKT0lOX1JPT01fUkVRVUVTVBABEhYKEkxFQVZF",
            "X1JPT01fUkVRVUVTVBACEhgKFERFU1RST1lfUk9PTV9SRVFVRVNUEAMSFQoR",
            "SEFMVF9ST09NX1JFUVVFU1QQBBIVChFHRVRfUk9PTVNfUkVRVUVTVBAFEhwK",
            "GEdFVF9ST09NX0RFVEFJTFNfUkVRVUVTVBAGEiEKHUtJQ0tfUExBWUVSX0ZS",
            "T01fUk9PTV9SRVFVRVNUEAcSGAoUU0VORF9NRVNTQUdFX1JFUVVFU1QQCBIW",
            "ChJHRVRfU1RBVFVTX1JFUVVFU1QQCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proxy.Proto.Models.GameRequestType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proxy.Proto.Models.GameRequest), global::Proxy.Proto.Models.GameRequest.Parser, new[]{ "GameRequestType", "Messsage", "Name" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameRequestType {
    /// <summary>
    ///  Messages
    /// </summary>
    [pbr::OriginalName("CREATE_ROOM_REQUEST")] CreateRoomRequest = 0,
    [pbr::OriginalName("JOIN_ROOM_REQUEST")] JoinRoomRequest = 1,
    [pbr::OriginalName("LEAVE_ROOM_REQUEST")] LeaveRoomRequest = 2,
    [pbr::OriginalName("DESTROY_ROOM_REQUEST")] DestroyRoomRequest = 3,
    [pbr::OriginalName("HALT_ROOM_REQUEST")] HaltRoomRequest = 4,
    [pbr::OriginalName("GET_ROOMS_REQUEST")] GetRoomsRequest = 5,
    [pbr::OriginalName("GET_ROOM_DETAILS_REQUEST")] GetRoomDetailsRequest = 6,
    [pbr::OriginalName("KICK_PLAYER_FROM_ROOM_REQUEST")] KickPlayerFromRoomRequest = 7,
    [pbr::OriginalName("SEND_MESSAGE_REQUEST")] SendMessageRequest = 8,
    [pbr::OriginalName("GET_STATUS_REQUEST")] GetStatusRequest = 9,
  }

  #endregion

  #region Messages
  public sealed partial class GameRequest : pb::IMessage<GameRequest> {
    private static readonly pb::MessageParser<GameRequest> _parser = new pb::MessageParser<GameRequest>(() => new GameRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proxy.Proto.Models.GameRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameRequest(GameRequest other) : this() {
      gameRequestType_ = other.gameRequestType_;
      messsage_ = other.messsage_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameRequest Clone() {
      return new GameRequest(this);
    }

    /// <summary>Field number for the "gameRequestType" field.</summary>
    public const int GameRequestTypeFieldNumber = 1;
    private global::Proxy.Proto.Models.GameRequestType gameRequestType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proxy.Proto.Models.GameRequestType GameRequestType {
      get { return gameRequestType_; }
      set {
        gameRequestType_ = value;
      }
    }

    /// <summary>Field number for the "messsage" field.</summary>
    public const int MesssageFieldNumber = 2;
    private pb::ByteString messsage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Messsage {
      get { return messsage_; }
      set {
        messsage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameRequestType != other.GameRequestType) return false;
      if (Messsage != other.Messsage) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GameRequestType != 0) hash ^= GameRequestType.GetHashCode();
      if (Messsage.Length != 0) hash ^= Messsage.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GameRequestType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GameRequestType);
      }
      if (Messsage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Messsage);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GameRequestType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GameRequestType);
      }
      if (Messsage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Messsage);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameRequest other) {
      if (other == null) {
        return;
      }
      if (other.GameRequestType != 0) {
        GameRequestType = other.GameRequestType;
      }
      if (other.Messsage.Length != 0) {
        Messsage = other.Messsage;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            gameRequestType_ = (global::Proxy.Proto.Models.GameRequestType) input.ReadEnum();
            break;
          }
          case 18: {
            Messsage = input.ReadBytes();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
