// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Notification.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proxy.Proto.Models {

  /// <summary>Holder for reflection information generated from Notification.proto</summary>
  public static partial class NotificationReflection {

    #region Descriptor
    /// <summary>File descriptor for Notification.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NotificationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJOb3RpZmljYXRpb24ucHJvdG8SEnByb3h5LnByb3RvLm1vZGVscyKaAQoM",
            "Tm90aWZpY2F0aW9uEg0KBWFwcElkGAEgASgJEg0KBXRpdGxlGAIgASgJEg0K",
            "BXNEZXNjGAMgASgJEgwKBERlc2MYBCABKAkSNgoGaW50ZW50GAUgASgOMiYu",
            "cHJveHkucHJvdG8ubW9kZWxzLk5vdGlmaWNhdGlvbkludGVudBIXCg9zaG93",
            "SWZJbnN0YWxsZWQYBiABKAgqWwoSTm90aWZpY2F0aW9uSW50ZW50EgwKCE9Q",
            "RU5fQVBQEAASDgoKRE9fTk9USElORxABEhIKDk9QRU5fQ09OVEFJTkVSEAIS",
            "EwoPT1BFTl9TVE9SRV9MSU5LEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proxy.Proto.Models.NotificationIntent), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proxy.Proto.Models.Notification), global::Proxy.Proto.Models.Notification.Parser, new[]{ "AppId", "Title", "SDesc", "Desc", "Intent", "ShowIfInstalled" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum NotificationIntent {
    [pbr::OriginalName("OPEN_APP")] OpenApp = 0,
    [pbr::OriginalName("DO_NOTHING")] DoNothing = 1,
    [pbr::OriginalName("OPEN_CONTAINER")] OpenContainer = 2,
    [pbr::OriginalName("OPEN_STORE_LINK")] OpenStoreLink = 3,
  }

  #endregion

  #region Messages
  public sealed partial class Notification : pb::IMessage<Notification> {
    private static readonly pb::MessageParser<Notification> _parser = new pb::MessageParser<Notification>(() => new Notification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Notification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proxy.Proto.Models.NotificationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Notification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Notification(Notification other) : this() {
      appId_ = other.appId_;
      title_ = other.title_;
      sDesc_ = other.sDesc_;
      desc_ = other.desc_;
      intent_ = other.intent_;
      showIfInstalled_ = other.showIfInstalled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Notification Clone() {
      return new Notification(this);
    }

    /// <summary>Field number for the "appId" field.</summary>
    public const int AppIdFieldNumber = 1;
    private string appId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppId {
      get { return appId_; }
      set {
        appId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sDesc" field.</summary>
    public const int SDescFieldNumber = 3;
    private string sDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SDesc {
      get { return sDesc_; }
      set {
        sDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 4;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "intent" field.</summary>
    public const int IntentFieldNumber = 5;
    private global::Proxy.Proto.Models.NotificationIntent intent_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proxy.Proto.Models.NotificationIntent Intent {
      get { return intent_; }
      set {
        intent_ = value;
      }
    }

    /// <summary>Field number for the "showIfInstalled" field.</summary>
    public const int ShowIfInstalledFieldNumber = 6;
    private bool showIfInstalled_;
    /// <summary>
    /// If true, show the notification if app_id is present in DB, else show it anyways
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ShowIfInstalled {
      get { return showIfInstalled_; }
      set {
        showIfInstalled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Notification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Notification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppId != other.AppId) return false;
      if (Title != other.Title) return false;
      if (SDesc != other.SDesc) return false;
      if (Desc != other.Desc) return false;
      if (Intent != other.Intent) return false;
      if (ShowIfInstalled != other.ShowIfInstalled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AppId.Length != 0) hash ^= AppId.GetHashCode();
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (SDesc.Length != 0) hash ^= SDesc.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (Intent != 0) hash ^= Intent.GetHashCode();
      if (ShowIfInstalled != false) hash ^= ShowIfInstalled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AppId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AppId);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (SDesc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SDesc);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Desc);
      }
      if (Intent != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Intent);
      }
      if (ShowIfInstalled != false) {
        output.WriteRawTag(48);
        output.WriteBool(ShowIfInstalled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AppId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppId);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (SDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SDesc);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (Intent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Intent);
      }
      if (ShowIfInstalled != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Notification other) {
      if (other == null) {
        return;
      }
      if (other.AppId.Length != 0) {
        AppId = other.AppId;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.SDesc.Length != 0) {
        SDesc = other.SDesc;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.Intent != 0) {
        Intent = other.Intent;
      }
      if (other.ShowIfInstalled != false) {
        ShowIfInstalled = other.ShowIfInstalled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AppId = input.ReadString();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            SDesc = input.ReadString();
            break;
          }
          case 34: {
            Desc = input.ReadString();
            break;
          }
          case 40: {
            intent_ = (global::Proxy.Proto.Models.NotificationIntent) input.ReadEnum();
            break;
          }
          case 48: {
            ShowIfInstalled = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
