// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AnalyticsEvent.proto

package com_example_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AnalyticsEvent struct {
	EventId              string   `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventPayload         string   `protobuf:"bytes,4,opt,name=eventPayload,proto3" json:"eventPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyticsEvent) Reset()         { *m = AnalyticsEvent{} }
func (m *AnalyticsEvent) String() string { return proto.CompactTextString(m) }
func (*AnalyticsEvent) ProtoMessage()    {}
func (*AnalyticsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_AnalyticsEvent_876a02f13d34e70b, []int{0}
}
func (m *AnalyticsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyticsEvent.Unmarshal(m, b)
}
func (m *AnalyticsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyticsEvent.Marshal(b, m, deterministic)
}
func (dst *AnalyticsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyticsEvent.Merge(dst, src)
}
func (m *AnalyticsEvent) XXX_Size() int {
	return xxx_messageInfo_AnalyticsEvent.Size(m)
}
func (m *AnalyticsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyticsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyticsEvent proto.InternalMessageInfo

func (m *AnalyticsEvent) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *AnalyticsEvent) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AnalyticsEvent) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *AnalyticsEvent) GetEventPayload() string {
	if m != nil {
		return m.EventPayload
	}
	return ""
}

func init() {
	proto.RegisterType((*AnalyticsEvent)(nil), "com.example.proto.AnalyticsEvent")
}

func init() {
	proto.RegisterFile("AnalyticsEvent.proto", fileDescriptor_AnalyticsEvent_876a02f13d34e70b)
}

var fileDescriptor_AnalyticsEvent_876a02f13d34e70b = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0xcc, 0x4b, 0xcc,
	0xa9, 0x2c, 0xc9, 0x4c, 0x2e, 0x76, 0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0x4c, 0xce, 0xcf, 0xd5, 0x4b, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x85, 0x08, 0x29,
	0x35, 0x31, 0x72, 0xf1, 0xa1, 0xaa, 0x15, 0x92, 0xe0, 0x62, 0x4f, 0x05, 0x31, 0x3c, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x11, 0x2e, 0xd6, 0xc4, 0x82, 0x02, 0xcf,
	0x14, 0x09, 0x26, 0xb0, 0x38, 0x84, 0x23, 0x24, 0xc3, 0xc5, 0x59, 0x92, 0x99, 0x9b, 0x5a, 0x5c,
	0x92, 0x98, 0x5b, 0x20, 0xc1, 0x0c, 0x96, 0x41, 0x08, 0x08, 0x29, 0x71, 0xf1, 0x80, 0xb5, 0x07,
	0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0xb0, 0x80, 0x15, 0xa0, 0x88, 0x25, 0xb1, 0x81, 0xdd,
	0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xa7, 0x13, 0x98, 0xb6, 0x00, 0x00, 0x00,
}
