// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GameEvents.proto

package proxy_proto_models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameEventType int32

const (
	GameEventType_ROOM_CREATED_EVENT   GameEventType = 0
	GameEventType_ROOM_JOINED_EVENT    GameEventType = 1
	GameEventType_ROOM_LEFT_EVENT      GameEventType = 2
	GameEventType_ROOM_DESTROYED_EVENT GameEventType = 3
	GameEventType_ROOM_FULL_EVENT      GameEventType = 4
	GameEventType_GAME_PAUSED_EVENT    GameEventType = 5
	GameEventType_GAME_RESUMED_EVENT   GameEventType = 6
	GameEventType_GAME_CREATED_EVENT   GameEventType = 7
	GameEventType_GAME_DESTROYED_EVENT GameEventType = 8
	GameEventType_GAME_FINISHED_EVENT  GameEventType = 9
	GameEventType_GAME_STOPPED_EVENT   GameEventType = 10
	GameEventType_GAME_MESSAGE_EVENT   GameEventType = 11
)

var GameEventType_name = map[int32]string{
	0:  "ROOM_CREATED_EVENT",
	1:  "ROOM_JOINED_EVENT",
	2:  "ROOM_LEFT_EVENT",
	3:  "ROOM_DESTROYED_EVENT",
	4:  "ROOM_FULL_EVENT",
	5:  "GAME_PAUSED_EVENT",
	6:  "GAME_RESUMED_EVENT",
	7:  "GAME_CREATED_EVENT",
	8:  "GAME_DESTROYED_EVENT",
	9:  "GAME_FINISHED_EVENT",
	10: "GAME_STOPPED_EVENT",
	11: "GAME_MESSAGE_EVENT",
}
var GameEventType_value = map[string]int32{
	"ROOM_CREATED_EVENT":   0,
	"ROOM_JOINED_EVENT":    1,
	"ROOM_LEFT_EVENT":      2,
	"ROOM_DESTROYED_EVENT": 3,
	"ROOM_FULL_EVENT":      4,
	"GAME_PAUSED_EVENT":    5,
	"GAME_RESUMED_EVENT":   6,
	"GAME_CREATED_EVENT":   7,
	"GAME_DESTROYED_EVENT": 8,
	"GAME_FINISHED_EVENT":  9,
	"GAME_STOPPED_EVENT":   10,
	"GAME_MESSAGE_EVENT":   11,
}

func (x GameEventType) String() string {
	return proto.EnumName(GameEventType_name, int32(x))
}
func (GameEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_GameEvents_a3977e72d2eb0fba, []int{0}
}

type GameEvent struct {
	GameEventType        GameEventType `protobuf:"varint,1,opt,name=gameEventType,proto3,enum=proxy.proto.models.GameEventType" json:"gameEventType,omitempty"`
	Messsage             []byte        `protobuf:"bytes,3,opt,name=messsage,proto3" json:"messsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_GameEvents_a3977e72d2eb0fba, []int{0}
}
func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (dst *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(dst, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

func (m *GameEvent) GetGameEventType() GameEventType {
	if m != nil {
		return m.GameEventType
	}
	return GameEventType_ROOM_CREATED_EVENT
}

func (m *GameEvent) GetMesssage() []byte {
	if m != nil {
		return m.Messsage
	}
	return nil
}

func init() {
	proto.RegisterType((*GameEvent)(nil), "proxy.proto.models.GameEvent")
	proto.RegisterEnum("proxy.proto.models.GameEventType", GameEventType_name, GameEventType_value)
}

func init() { proto.RegisterFile("GameEvents.proto", fileDescriptor_GameEvents_a3977e72d2eb0fba) }

var fileDescriptor_GameEvents_a3977e72d2eb0fba = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0x4d, 0x4f, 0xb3, 0x40,
	0x10, 0x07, 0xf0, 0x87, 0xf6, 0xb1, 0xb6, 0xa3, 0xd5, 0x3a, 0xf5, 0x85, 0x78, 0xaa, 0x9e, 0x1a,
	0x0f, 0x1c, 0xf4, 0x13, 0x10, 0x3b, 0x20, 0x86, 0xb7, 0xec, 0x2e, 0x26, 0x9e, 0x48, 0x8d, 0x9b,
	0x5e, 0x44, 0x48, 0x69, 0x8c, 0xfd, 0x4e, 0x7e, 0x48, 0xc3, 0x8a, 0x13, 0xd1, 0xe3, 0xfc, 0xf6,
	0x3f, 0x2f, 0x59, 0x98, 0xf8, 0xcb, 0x42, 0xd3, 0x9b, 0x7e, 0xdd, 0xd4, 0x4e, 0xb5, 0x2e, 0x37,
	0x25, 0x62, 0xb5, 0x2e, 0xdf, 0xb7, 0x5f, 0x85, 0x53, 0x94, 0xcf, 0xfa, 0xa5, 0xbe, 0xac, 0x60,
	0xc4, 0x39, 0xf4, 0x61, 0xbc, 0xfa, 0x2e, 0xd4, 0xb6, 0xd2, 0xb6, 0x35, 0xb3, 0xe6, 0x07, 0xd7,
	0x17, 0xce, 0xdf, 0x46, 0xc7, 0xff, 0x19, 0x14, 0xdd, 0x3e, 0x3c, 0x87, 0x61, 0xa1, 0xeb, 0xba,
	0x5e, 0xae, 0xb4, 0xdd, 0x9f, 0x59, 0xf3, 0x7d, 0xc1, 0xf5, 0xd5, 0x47, 0x0f, 0xc6, 0x9d, 0x66,
	0x3c, 0x05, 0x14, 0x49, 0x12, 0xe5, 0xb7, 0x82, 0x5c, 0x45, 0x8b, 0x9c, 0x1e, 0x28, 0x56, 0x93,
	0x7f, 0x78, 0x02, 0x47, 0xc6, 0xef, 0x93, 0x20, 0x66, 0xb6, 0x70, 0x0a, 0x87, 0x86, 0x43, 0xf2,
	0x54, 0x8b, 0x3d, 0xb4, 0xe1, 0xd8, 0xe0, 0x82, 0xa4, 0x12, 0xc9, 0x23, 0xc7, 0xfb, 0x1c, 0xf7,
	0xb2, 0x30, 0x6c, 0xf1, 0x7f, 0x33, 0xda, 0x77, 0x23, 0xca, 0x53, 0x37, 0x93, 0x9c, 0xdd, 0x69,
	0x2e, 0x31, 0x2c, 0x48, 0x66, 0x11, 0xfb, 0x80, 0xbd, 0x7b, 0xe1, 0x6e, 0xb3, 0xd5, 0xf8, 0xef,
	0xad, 0x43, 0x3c, 0x83, 0xa9, 0x79, 0xf1, 0x82, 0x38, 0x90, 0x77, 0xfc, 0x30, 0xe2, 0x51, 0x52,
	0x25, 0x69, 0xca, 0x0e, 0xec, 0x11, 0x49, 0xe9, 0xfa, 0xd4, 0xfa, 0xde, 0xd3, 0xc0, 0xfc, 0xfa,
	0xcd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x80, 0xbc, 0x7e, 0xcf, 0x01, 0x00, 0x00,
}
