// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GameResponse.proto

package proxy_proto_models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameResponseType int32

const (
	GameResponseType_CREATE_ROOM_RESPONSE           GameResponseType = 0
	GameResponseType_JOIN_ROOM_RESPONSE             GameResponseType = 1
	GameResponseType_LEAVE_ROOM_RESPONSE            GameResponseType = 2
	GameResponseType_DESTROY_ROOM_RESPONSE          GameResponseType = 3
	GameResponseType_HALT_ROOM_RESPONSE             GameResponseType = 4
	GameResponseType_GET_ROOMS_RESPONSE             GameResponseType = 5
	GameResponseType_GET_ROOM_DETAILS_RESPONSE      GameResponseType = 6
	GameResponseType_KICK_PLAYER_FROM_ROOM_RESPONSE GameResponseType = 7
	GameResponseType_SEND_MESSAGE_RESPONSE          GameResponseType = 8
	GameResponseType_GET_STATUS_RESPONSE            GameResponseType = 9
)

var GameResponseType_name = map[int32]string{
	0: "CREATE_ROOM_RESPONSE",
	1: "JOIN_ROOM_RESPONSE",
	2: "LEAVE_ROOM_RESPONSE",
	3: "DESTROY_ROOM_RESPONSE",
	4: "HALT_ROOM_RESPONSE",
	5: "GET_ROOMS_RESPONSE",
	6: "GET_ROOM_DETAILS_RESPONSE",
	7: "KICK_PLAYER_FROM_ROOM_RESPONSE",
	8: "SEND_MESSAGE_RESPONSE",
	9: "GET_STATUS_RESPONSE",
}
var GameResponseType_value = map[string]int32{
	"CREATE_ROOM_RESPONSE":           0,
	"JOIN_ROOM_RESPONSE":             1,
	"LEAVE_ROOM_RESPONSE":            2,
	"DESTROY_ROOM_RESPONSE":          3,
	"HALT_ROOM_RESPONSE":             4,
	"GET_ROOMS_RESPONSE":             5,
	"GET_ROOM_DETAILS_RESPONSE":      6,
	"KICK_PLAYER_FROM_ROOM_RESPONSE": 7,
	"SEND_MESSAGE_RESPONSE":          8,
	"GET_STATUS_RESPONSE":            9,
}

func (x GameResponseType) String() string {
	return proto.EnumName(GameResponseType_name, int32(x))
}
func (GameResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_GameResponse_5a4e7f6cb02f880f, []int{0}
}

type GameResponse struct {
	GameResponseType     GameResponseType `protobuf:"varint,1,opt,name=gameResponseType,proto3,enum=proxy.proto.models.GameResponseType" json:"gameResponseType,omitempty"`
	Success              bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Messsage             []byte           `protobuf:"bytes,3,opt,name=messsage,proto3" json:"messsage,omitempty"`
	Name                 string           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_GameResponse_5a4e7f6cb02f880f, []int{0}
}
func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (dst *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(dst, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetGameResponseType() GameResponseType {
	if m != nil {
		return m.GameResponseType
	}
	return GameResponseType_CREATE_ROOM_RESPONSE
}

func (m *GameResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GameResponse) GetMesssage() []byte {
	if m != nil {
		return m.Messsage
	}
	return nil
}

func (m *GameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GameResponse)(nil), "proxy.proto.models.GameResponse")
	proto.RegisterEnum("proxy.proto.models.GameResponseType", GameResponseType_name, GameResponseType_value)
}

func init() { proto.RegisterFile("GameResponse.proto", fileDescriptor_GameResponse_5a4e7f6cb02f880f) }

var fileDescriptor_GameResponse_5a4e7f6cb02f880f = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x86, 0xbf, 0x01, 0x3e, 0x7e, 0x4e, 0x88, 0x21, 0xc7, 0xbf, 0x62, 0xa2, 0x69, 0x88, 0x8b,
	0xc6, 0x45, 0x17, 0x7a, 0x05, 0x13, 0x38, 0x56, 0xa4, 0x50, 0x32, 0x33, 0x9a, 0xb0, 0x6a, 0x10,
	0x27, 0x6c, 0x2c, 0x6d, 0x18, 0x4d, 0xe4, 0x6a, 0xdc, 0x7b, 0x95, 0x66, 0x20, 0x48, 0x6d, 0x77,
	0xf3, 0x3e, 0xe7, 0xbc, 0x4f, 0x66, 0x32, 0x80, 0xc1, 0x3c, 0xd1, 0x42, 0x9b, 0x2c, 0x5d, 0x19,
	0xed, 0x67, 0xeb, 0xf4, 0x3d, 0x45, 0xcc, 0xd6, 0xe9, 0xe7, 0x66, 0x17, 0xfc, 0x24, 0x7d, 0xd5,
	0x6f, 0xa6, 0xf7, 0xcd, 0xa0, 0x9d, 0x5f, 0xc5, 0x29, 0x74, 0x96, 0xb9, 0xac, 0x36, 0x99, 0x76,
	0x98, 0xcb, 0xbc, 0xa3, 0xdb, 0x6b, 0xbf, 0xdc, 0xf7, 0x83, 0xc2, 0xae, 0x28, 0xb5, 0xd1, 0x81,
	0x86, 0xf9, 0x58, 0x2c, 0xb4, 0x31, 0x4e, 0xc5, 0x65, 0x5e, 0x53, 0xec, 0x23, 0x5e, 0x40, 0x33,
	0xd1, 0xc6, 0x98, 0xf9, 0x52, 0x3b, 0x55, 0x97, 0x79, 0x6d, 0xf1, 0x9b, 0x11, 0xa1, 0xb6, 0x9a,
	0x27, 0xda, 0xa9, 0xb9, 0xcc, 0x6b, 0x89, 0xed, 0xf9, 0xe6, 0xab, 0x02, 0x9d, 0xa0, 0xac, 0x3f,
	0xe9, 0x0b, 0xe2, 0x8a, 0x62, 0x11, 0x45, 0xe3, 0x58, 0x90, 0x9c, 0x46, 0x13, 0x49, 0x9d, 0x7f,
	0x78, 0x06, 0xf8, 0x18, 0x0d, 0x27, 0x05, 0xce, 0xf0, 0x1c, 0x8e, 0x43, 0xe2, 0xcf, 0xc5, 0x42,
	0x05, 0xbb, 0x70, 0x3a, 0x20, 0xa9, 0x44, 0x34, 0x2b, 0x8c, 0xaa, 0xd6, 0xf5, 0xc0, 0x43, 0x55,
	0xe0, 0x35, 0xcb, 0x03, 0xda, 0x61, 0x79, 0xe0, 0xff, 0xf1, 0x12, 0xba, 0x7b, 0x1e, 0x0f, 0x48,
	0xf1, 0x61, 0x98, 0x1b, 0xd7, 0xb1, 0x07, 0x57, 0xa3, 0x61, 0x7f, 0x14, 0x4f, 0x43, 0x3e, 0x23,
	0x11, 0xdf, 0x0b, 0x6b, 0xfd, 0xa3, 0x6e, 0xd8, 0xdb, 0x48, 0x9a, 0x0c, 0xe2, 0x31, 0x49, 0xc9,
	0x03, 0x3a, 0x8c, 0x9a, 0xf6, 0x05, 0xd6, 0x2e, 0x15, 0x57, 0x4f, 0x39, 0x6f, 0xeb, 0xa5, 0xbe,
	0xfd, 0x9c, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xcd, 0x48, 0x27, 0xff, 0x01, 0x00,
	0x00,
}
