// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GameRequest.proto

package proxy_proto_models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameRequestType int32

const (
	//  Messages
	GameRequestType_CREATE_ROOM_REQUEST           GameRequestType = 0
	GameRequestType_JOIN_ROOM_REQUEST             GameRequestType = 1
	GameRequestType_LEAVE_ROOM_REQUEST            GameRequestType = 2
	GameRequestType_DESTROY_ROOM_REQUEST          GameRequestType = 3
	GameRequestType_HALT_ROOM_REQUEST             GameRequestType = 4
	GameRequestType_GET_ROOMS_REQUEST             GameRequestType = 5
	GameRequestType_GET_ROOM_DETAILS_REQUEST      GameRequestType = 6
	GameRequestType_KICK_PLAYER_FROM_ROOM_REQUEST GameRequestType = 7
	GameRequestType_SEND_MESSAGE_REQUEST          GameRequestType = 8
	GameRequestType_GET_STATUS_REQUEST            GameRequestType = 9
)

var GameRequestType_name = map[int32]string{
	0: "CREATE_ROOM_REQUEST",
	1: "JOIN_ROOM_REQUEST",
	2: "LEAVE_ROOM_REQUEST",
	3: "DESTROY_ROOM_REQUEST",
	4: "HALT_ROOM_REQUEST",
	5: "GET_ROOMS_REQUEST",
	6: "GET_ROOM_DETAILS_REQUEST",
	7: "KICK_PLAYER_FROM_ROOM_REQUEST",
	8: "SEND_MESSAGE_REQUEST",
	9: "GET_STATUS_REQUEST",
}
var GameRequestType_value = map[string]int32{
	"CREATE_ROOM_REQUEST":           0,
	"JOIN_ROOM_REQUEST":             1,
	"LEAVE_ROOM_REQUEST":            2,
	"DESTROY_ROOM_REQUEST":          3,
	"HALT_ROOM_REQUEST":             4,
	"GET_ROOMS_REQUEST":             5,
	"GET_ROOM_DETAILS_REQUEST":      6,
	"KICK_PLAYER_FROM_ROOM_REQUEST": 7,
	"SEND_MESSAGE_REQUEST":          8,
	"GET_STATUS_REQUEST":            9,
}

func (x GameRequestType) String() string {
	return proto.EnumName(GameRequestType_name, int32(x))
}
func (GameRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_GameRequest_f0dd9d07ffd0d1c9, []int{0}
}

type GameRequest struct {
	GameRequestType      GameRequestType `protobuf:"varint,1,opt,name=gameRequestType,proto3,enum=proxy.proto.models.GameRequestType" json:"gameRequestType,omitempty"`
	Messsage             []byte          `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_GameRequest_f0dd9d07ffd0d1c9, []int{0}
}
func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (dst *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(dst, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetGameRequestType() GameRequestType {
	if m != nil {
		return m.GameRequestType
	}
	return GameRequestType_CREATE_ROOM_REQUEST
}

func (m *GameRequest) GetMesssage() []byte {
	if m != nil {
		return m.Messsage
	}
	return nil
}

func (m *GameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GameRequest)(nil), "proxy.proto.models.GameRequest")
	proto.RegisterEnum("proxy.proto.models.GameRequestType", GameRequestType_name, GameRequestType_value)
}

func init() { proto.RegisterFile("GameRequest.proto", fileDescriptor_GameRequest_f0dd9d07ffd0d1c9) }

var fileDescriptor_GameRequest_f0dd9d07ffd0d1c9 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0x05, 0x5e, 0x84, 0xd1, 0x88, 0x8c, 0xff, 0x1a, 0xa3, 0x09, 0xea, 0x85, 0x78,
	0xe8, 0x41, 0x3f, 0xc1, 0x06, 0xc6, 0x8a, 0x14, 0xaa, 0xbb, 0x8b, 0x09, 0xa7, 0x4d, 0x8d, 0x1b,
	0x2e, 0xd6, 0x56, 0x8a, 0x89, 0x7c, 0x07, 0x8f, 0x7e, 0x60, 0xb3, 0x10, 0x5b, 0x5a, 0x6f, 0x3b,
	0xbf, 0xe7, 0x99, 0x5f, 0x26, 0x0b, 0x6d, 0x2f, 0x8c, 0x8c, 0x30, 0xef, 0x1f, 0x26, 0x5d, 0xb8,
	0xc9, 0x3c, 0x5e, 0xc4, 0x88, 0xc9, 0x3c, 0xfe, 0x5c, 0xae, 0x07, 0x37, 0x8a, 0x5f, 0xcc, 0x6b,
	0x7a, 0xf1, 0xc5, 0x60, 0x7b, 0xa3, 0x89, 0x23, 0x68, 0xcd, 0xf2, 0x51, 0x2d, 0x13, 0xe3, 0xb0,
	0x0e, 0xeb, 0xee, 0x5e, 0x5f, 0xba, 0x7f, 0xb7, 0x5d, 0xaf, 0x58, 0x15, 0xe5, 0x5d, 0x3c, 0x81,
	0x46, 0x64, 0xd2, 0x34, 0x0d, 0x67, 0xc6, 0xa9, 0x74, 0x58, 0x77, 0x47, 0x64, 0x33, 0x22, 0xd4,
	0xde, 0xc2, 0xc8, 0x38, 0xd5, 0x0e, 0xeb, 0x36, 0xc5, 0xea, 0x7d, 0xf5, 0x5d, 0x81, 0x56, 0x49,
	0x8a, 0xc7, 0xb0, 0xdf, 0x13, 0xc4, 0x15, 0x69, 0x11, 0x04, 0x23, 0x2d, 0xe8, 0x71, 0x42, 0x52,
	0xed, 0xfd, 0xc3, 0x43, 0x68, 0xdf, 0x07, 0x83, 0x71, 0x11, 0x33, 0x3c, 0x02, 0xf4, 0x89, 0x3f,
	0x95, 0xea, 0x15, 0x74, 0xe0, 0xa0, 0x4f, 0x52, 0x89, 0x60, 0x5a, 0x4c, 0xaa, 0x56, 0x74, 0xc7,
	0x7d, 0x55, 0xc4, 0x35, 0x8b, 0x3d, 0x5a, 0x53, 0x99, 0xe1, 0xff, 0x78, 0x0a, 0xce, 0x2f, 0xd6,
	0x7d, 0x52, 0x7c, 0xe0, 0xe7, 0x69, 0x1d, 0xcf, 0xe1, 0x6c, 0x38, 0xe8, 0x0d, 0xf5, 0x83, 0xcf,
	0xa7, 0x24, 0xf4, 0xad, 0xb0, 0xca, 0x4d, 0xef, 0x96, 0x3d, 0x44, 0xd2, 0xb8, 0xaf, 0x47, 0x24,
	0x25, 0xf7, 0x28, 0x4b, 0x1a, 0xf6, 0x74, 0xab, 0x96, 0x8a, 0xab, 0x49, 0x2e, 0x6d, 0x3e, 0xd7,
	0x57, 0xbf, 0x7e, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x2d, 0x51, 0xe4, 0xd5, 0x01, 0x00,
	0x00,
}
