// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MultiplayerGame.proto

package com_example_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MultiplayerMessageType int32

const (
	//  Messages
	MultiplayerMessageType_ROOM_CREATE       MultiplayerMessageType = 0
	MultiplayerMessageType_ROOM_JOIN         MultiplayerMessageType = 1
	MultiplayerMessageType_ROOM_LEAVE        MultiplayerMessageType = 2
	MultiplayerMessageType_ROOM_DESTROY      MultiplayerMessageType = 3
	MultiplayerMessageType_ROOM_HALT         MultiplayerMessageType = 4
	MultiplayerMessageType_ROOM_GET_DETAILS  MultiplayerMessageType = 5
	MultiplayerMessageType_ROOM_ADD_PLAYER   MultiplayerMessageType = 6
	MultiplayerMessageType_ROOM_KICK_PLAYER  MultiplayerMessageType = 7
	MultiplayerMessageType_ROOM_SEND_MESSAGE MultiplayerMessageType = 8
	MultiplayerMessageType_ROOM_GET_PLAYERS  MultiplayerMessageType = 9
	MultiplayerMessageType_PLAYERS_IN_ROOM   MultiplayerMessageType = 10
	//  Events
	MultiplayerMessageType_ROOM_CREATE_EVENT       MultiplayerMessageType = 11
	MultiplayerMessageType_ROOM_JOIN_EVENT         MultiplayerMessageType = 12
	MultiplayerMessageType_ROOM_LEAVE_EVENT        MultiplayerMessageType = 13
	MultiplayerMessageType_ROOM_DESTROY_EVENT      MultiplayerMessageType = 14
	MultiplayerMessageType_ROOM_HALT_EVENT         MultiplayerMessageType = 15
	MultiplayerMessageType_ROOM_GET_DETAILS_EVENT  MultiplayerMessageType = 16
	MultiplayerMessageType_ROOM_ADD_PLAYER_EVENT   MultiplayerMessageType = 17
	MultiplayerMessageType_ROOM_KICK_PLAYER_EVENT  MultiplayerMessageType = 18
	MultiplayerMessageType_ROOM_SEND_MESSAGE_EVENT MultiplayerMessageType = 19
)

var MultiplayerMessageType_name = map[int32]string{
	0:  "ROOM_CREATE",
	1:  "ROOM_JOIN",
	2:  "ROOM_LEAVE",
	3:  "ROOM_DESTROY",
	4:  "ROOM_HALT",
	5:  "ROOM_GET_DETAILS",
	6:  "ROOM_ADD_PLAYER",
	7:  "ROOM_KICK_PLAYER",
	8:  "ROOM_SEND_MESSAGE",
	9:  "ROOM_GET_PLAYERS",
	10: "PLAYERS_IN_ROOM",
	11: "ROOM_CREATE_EVENT",
	12: "ROOM_JOIN_EVENT",
	13: "ROOM_LEAVE_EVENT",
	14: "ROOM_DESTROY_EVENT",
	15: "ROOM_HALT_EVENT",
	16: "ROOM_GET_DETAILS_EVENT",
	17: "ROOM_ADD_PLAYER_EVENT",
	18: "ROOM_KICK_PLAYER_EVENT",
	19: "ROOM_SEND_MESSAGE_EVENT",
}
var MultiplayerMessageType_value = map[string]int32{
	"ROOM_CREATE":             0,
	"ROOM_JOIN":               1,
	"ROOM_LEAVE":              2,
	"ROOM_DESTROY":            3,
	"ROOM_HALT":               4,
	"ROOM_GET_DETAILS":        5,
	"ROOM_ADD_PLAYER":         6,
	"ROOM_KICK_PLAYER":        7,
	"ROOM_SEND_MESSAGE":       8,
	"ROOM_GET_PLAYERS":        9,
	"PLAYERS_IN_ROOM":         10,
	"ROOM_CREATE_EVENT":       11,
	"ROOM_JOIN_EVENT":         12,
	"ROOM_LEAVE_EVENT":        13,
	"ROOM_DESTROY_EVENT":      14,
	"ROOM_HALT_EVENT":         15,
	"ROOM_GET_DETAILS_EVENT":  16,
	"ROOM_ADD_PLAYER_EVENT":   17,
	"ROOM_KICK_PLAYER_EVENT":  18,
	"ROOM_SEND_MESSAGE_EVENT": 19,
}

func (x MultiplayerMessageType) String() string {
	return proto.EnumName(MultiplayerMessageType_name, int32(x))
}
func (MultiplayerMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{0}
}

type MultiplayerMessage struct {
	MultiplayerMessageType MultiplayerMessageType `protobuf:"varint,1,opt,name=multiplayerMessageType,proto3,enum=com.example.proto.MultiplayerMessageType" json:"multiplayerMessageType,omitempty"`
	Messsage               []byte                 `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *MultiplayerMessage) Reset()         { *m = MultiplayerMessage{} }
func (m *MultiplayerMessage) String() string { return proto.CompactTextString(m) }
func (*MultiplayerMessage) ProtoMessage()    {}
func (*MultiplayerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{0}
}
func (m *MultiplayerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplayerMessage.Unmarshal(m, b)
}
func (m *MultiplayerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplayerMessage.Marshal(b, m, deterministic)
}
func (dst *MultiplayerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplayerMessage.Merge(dst, src)
}
func (m *MultiplayerMessage) XXX_Size() int {
	return xxx_messageInfo_MultiplayerMessage.Size(m)
}
func (m *MultiplayerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplayerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplayerMessage proto.InternalMessageInfo

func (m *MultiplayerMessage) GetMultiplayerMessageType() MultiplayerMessageType {
	if m != nil {
		return m.MultiplayerMessageType
	}
	return MultiplayerMessageType_ROOM_CREATE
}

func (m *MultiplayerMessage) GetMesssage() []byte {
	if m != nil {
		return m.Messsage
	}
	return nil
}

type RoomCreate struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	RoomSize             string   `protobuf:"bytes,3,opt,name=roomSize,proto3" json:"roomSize,omitempty"`
	RoomTTL              string   `protobuf:"bytes,4,opt,name=roomTTL,proto3" json:"roomTTL,omitempty"`
	RoomId               string   `protobuf:"bytes,5,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GameId               string   `protobuf:"bytes,6,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreate) Reset()         { *m = RoomCreate{} }
func (m *RoomCreate) String() string { return proto.CompactTextString(m) }
func (*RoomCreate) ProtoMessage()    {}
func (*RoomCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{1}
}
func (m *RoomCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreate.Unmarshal(m, b)
}
func (m *RoomCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreate.Marshal(b, m, deterministic)
}
func (dst *RoomCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreate.Merge(dst, src)
}
func (m *RoomCreate) XXX_Size() int {
	return xxx_messageInfo_RoomCreate.Size(m)
}
func (m *RoomCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreate.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreate proto.InternalMessageInfo

func (m *RoomCreate) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

func (m *RoomCreate) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomCreate) GetRoomSize() string {
	if m != nil {
		return m.RoomSize
	}
	return ""
}

func (m *RoomCreate) GetRoomTTL() string {
	if m != nil {
		return m.RoomTTL
	}
	return ""
}

func (m *RoomCreate) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomCreate) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type RoomJoin struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomJoin) Reset()         { *m = RoomJoin{} }
func (m *RoomJoin) String() string { return proto.CompactTextString(m) }
func (*RoomJoin) ProtoMessage()    {}
func (*RoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{2}
}
func (m *RoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomJoin.Unmarshal(m, b)
}
func (m *RoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomJoin.Marshal(b, m, deterministic)
}
func (dst *RoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomJoin.Merge(dst, src)
}
func (m *RoomJoin) XXX_Size() int {
	return xxx_messageInfo_RoomJoin.Size(m)
}
func (m *RoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_RoomJoin proto.InternalMessageInfo

func (m *RoomJoin) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

type RoomLeave struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomLeave) Reset()         { *m = RoomLeave{} }
func (m *RoomLeave) String() string { return proto.CompactTextString(m) }
func (*RoomLeave) ProtoMessage()    {}
func (*RoomLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{3}
}
func (m *RoomLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomLeave.Unmarshal(m, b)
}
func (m *RoomLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomLeave.Marshal(b, m, deterministic)
}
func (dst *RoomLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomLeave.Merge(dst, src)
}
func (m *RoomLeave) XXX_Size() int {
	return xxx_messageInfo_RoomLeave.Size(m)
}
func (m *RoomLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomLeave.DiscardUnknown(m)
}

var xxx_messageInfo_RoomLeave proto.InternalMessageInfo

func (m *RoomLeave) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

type RoomDestroy struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDestroy) Reset()         { *m = RoomDestroy{} }
func (m *RoomDestroy) String() string { return proto.CompactTextString(m) }
func (*RoomDestroy) ProtoMessage()    {}
func (*RoomDestroy) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{4}
}
func (m *RoomDestroy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDestroy.Unmarshal(m, b)
}
func (m *RoomDestroy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDestroy.Marshal(b, m, deterministic)
}
func (dst *RoomDestroy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDestroy.Merge(dst, src)
}
func (m *RoomDestroy) XXX_Size() int {
	return xxx_messageInfo_RoomDestroy.Size(m)
}
func (m *RoomDestroy) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDestroy.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDestroy proto.InternalMessageInfo

func (m *RoomDestroy) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

type RoomHalt struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomHalt) Reset()         { *m = RoomHalt{} }
func (m *RoomHalt) String() string { return proto.CompactTextString(m) }
func (*RoomHalt) ProtoMessage()    {}
func (*RoomHalt) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{5}
}
func (m *RoomHalt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomHalt.Unmarshal(m, b)
}
func (m *RoomHalt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomHalt.Marshal(b, m, deterministic)
}
func (dst *RoomHalt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomHalt.Merge(dst, src)
}
func (m *RoomHalt) XXX_Size() int {
	return xxx_messageInfo_RoomHalt.Size(m)
}
func (m *RoomHalt) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomHalt.DiscardUnknown(m)
}

var xxx_messageInfo_RoomHalt proto.InternalMessageInfo

func (m *RoomHalt) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

type RoomGetDetails struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomGetDetails) Reset()         { *m = RoomGetDetails{} }
func (m *RoomGetDetails) String() string { return proto.CompactTextString(m) }
func (*RoomGetDetails) ProtoMessage()    {}
func (*RoomGetDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{6}
}
func (m *RoomGetDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomGetDetails.Unmarshal(m, b)
}
func (m *RoomGetDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomGetDetails.Marshal(b, m, deterministic)
}
func (dst *RoomGetDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomGetDetails.Merge(dst, src)
}
func (m *RoomGetDetails) XXX_Size() int {
	return xxx_messageInfo_RoomGetDetails.Size(m)
}
func (m *RoomGetDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomGetDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RoomGetDetails proto.InternalMessageInfo

func (m *RoomGetDetails) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

func (m *RoomGetDetails) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

type RoomAddPlayer struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAddPlayer) Reset()         { *m = RoomAddPlayer{} }
func (m *RoomAddPlayer) String() string { return proto.CompactTextString(m) }
func (*RoomAddPlayer) ProtoMessage()    {}
func (*RoomAddPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{7}
}
func (m *RoomAddPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAddPlayer.Unmarshal(m, b)
}
func (m *RoomAddPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAddPlayer.Marshal(b, m, deterministic)
}
func (dst *RoomAddPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAddPlayer.Merge(dst, src)
}
func (m *RoomAddPlayer) XXX_Size() int {
	return xxx_messageInfo_RoomAddPlayer.Size(m)
}
func (m *RoomAddPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAddPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAddPlayer proto.InternalMessageInfo

func (m *RoomAddPlayer) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

func (m *RoomAddPlayer) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type RoomKickPlayer struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomKickPlayer) Reset()         { *m = RoomKickPlayer{} }
func (m *RoomKickPlayer) String() string { return proto.CompactTextString(m) }
func (*RoomKickPlayer) ProtoMessage()    {}
func (*RoomKickPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{8}
}
func (m *RoomKickPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomKickPlayer.Unmarshal(m, b)
}
func (m *RoomKickPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomKickPlayer.Marshal(b, m, deterministic)
}
func (dst *RoomKickPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomKickPlayer.Merge(dst, src)
}
func (m *RoomKickPlayer) XXX_Size() int {
	return xxx_messageInfo_RoomKickPlayer.Size(m)
}
func (m *RoomKickPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomKickPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RoomKickPlayer proto.InternalMessageInfo

func (m *RoomKickPlayer) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

func (m *RoomKickPlayer) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type RoomSendMessage struct {
	RoomToken            string   `protobuf:"bytes,1,opt,name=roomToken,proto3" json:"roomToken,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomSendMessage) Reset()         { *m = RoomSendMessage{} }
func (m *RoomSendMessage) String() string { return proto.CompactTextString(m) }
func (*RoomSendMessage) ProtoMessage()    {}
func (*RoomSendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{9}
}
func (m *RoomSendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSendMessage.Unmarshal(m, b)
}
func (m *RoomSendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSendMessage.Marshal(b, m, deterministic)
}
func (dst *RoomSendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSendMessage.Merge(dst, src)
}
func (m *RoomSendMessage) XXX_Size() int {
	return xxx_messageInfo_RoomSendMessage.Size(m)
}
func (m *RoomSendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSendMessage proto.InternalMessageInfo

func (m *RoomSendMessage) GetRoomToken() string {
	if m != nil {
		return m.RoomToken
	}
	return ""
}

func (m *RoomSendMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RoomGetPlayers struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomGetPlayers) Reset()         { *m = RoomGetPlayers{} }
func (m *RoomGetPlayers) String() string { return proto.CompactTextString(m) }
func (*RoomGetPlayers) ProtoMessage()    {}
func (*RoomGetPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{10}
}
func (m *RoomGetPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomGetPlayers.Unmarshal(m, b)
}
func (m *RoomGetPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomGetPlayers.Marshal(b, m, deterministic)
}
func (dst *RoomGetPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomGetPlayers.Merge(dst, src)
}
func (m *RoomGetPlayers) XXX_Size() int {
	return xxx_messageInfo_RoomGetPlayers.Size(m)
}
func (m *RoomGetPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomGetPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_RoomGetPlayers proto.InternalMessageInfo

func (m *RoomGetPlayers) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type PlayersInRoom struct {
	Players              []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayersInRoom) Reset()         { *m = PlayersInRoom{} }
func (m *PlayersInRoom) String() string { return proto.CompactTextString(m) }
func (*PlayersInRoom) ProtoMessage()    {}
func (*PlayersInRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{11}
}
func (m *PlayersInRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersInRoom.Unmarshal(m, b)
}
func (m *PlayersInRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersInRoom.Marshal(b, m, deterministic)
}
func (dst *PlayersInRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersInRoom.Merge(dst, src)
}
func (m *PlayersInRoom) XXX_Size() int {
	return xxx_messageInfo_PlayersInRoom.Size(m)
}
func (m *PlayersInRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersInRoom.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersInRoom proto.InternalMessageInfo

func (m *PlayersInRoom) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PlayersInRoom) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type GenericEvent struct {
	EventType            MultiplayerMessageType `protobuf:"varint,1,opt,name=eventType,proto3,enum=com.example.proto.MultiplayerMessageType" json:"eventType,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GenericEvent) Reset()         { *m = GenericEvent{} }
func (m *GenericEvent) String() string { return proto.CompactTextString(m) }
func (*GenericEvent) ProtoMessage()    {}
func (*GenericEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_MultiplayerGame_32e22cd5e5ed5472, []int{12}
}
func (m *GenericEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericEvent.Unmarshal(m, b)
}
func (m *GenericEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericEvent.Marshal(b, m, deterministic)
}
func (dst *GenericEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericEvent.Merge(dst, src)
}
func (m *GenericEvent) XXX_Size() int {
	return xxx_messageInfo_GenericEvent.Size(m)
}
func (m *GenericEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GenericEvent proto.InternalMessageInfo

func (m *GenericEvent) GetEventType() MultiplayerMessageType {
	if m != nil {
		return m.EventType
	}
	return MultiplayerMessageType_ROOM_CREATE
}

func (m *GenericEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MultiplayerMessage)(nil), "com.example.proto.MultiplayerMessage")
	proto.RegisterType((*RoomCreate)(nil), "com.example.proto.RoomCreate")
	proto.RegisterType((*RoomJoin)(nil), "com.example.proto.RoomJoin")
	proto.RegisterType((*RoomLeave)(nil), "com.example.proto.RoomLeave")
	proto.RegisterType((*RoomDestroy)(nil), "com.example.proto.RoomDestroy")
	proto.RegisterType((*RoomHalt)(nil), "com.example.proto.RoomHalt")
	proto.RegisterType((*RoomGetDetails)(nil), "com.example.proto.RoomGetDetails")
	proto.RegisterType((*RoomAddPlayer)(nil), "com.example.proto.RoomAddPlayer")
	proto.RegisterType((*RoomKickPlayer)(nil), "com.example.proto.RoomKickPlayer")
	proto.RegisterType((*RoomSendMessage)(nil), "com.example.proto.RoomSendMessage")
	proto.RegisterType((*RoomGetPlayers)(nil), "com.example.proto.RoomGetPlayers")
	proto.RegisterType((*PlayersInRoom)(nil), "com.example.proto.PlayersInRoom")
	proto.RegisterType((*GenericEvent)(nil), "com.example.proto.GenericEvent")
	proto.RegisterEnum("com.example.proto.MultiplayerMessageType", MultiplayerMessageType_name, MultiplayerMessageType_value)
}

func init() {
	proto.RegisterFile("MultiplayerGame.proto", fileDescriptor_MultiplayerGame_32e22cd5e5ed5472)
}

var fileDescriptor_MultiplayerGame_32e22cd5e5ed5472 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdb, 0x6e, 0x9b, 0x40,
	0x10, 0x2d, 0x71, 0xe2, 0x84, 0x89, 0x2f, 0x9b, 0x4d, 0xe3, 0xd2, 0xb4, 0x0f, 0x11, 0x4f, 0x49,
	0x5b, 0xf9, 0xa1, 0xfd, 0x02, 0x64, 0x56, 0x18, 0x1b, 0xdb, 0x11, 0xa0, 0x48, 0x79, 0x42, 0xd4,
	0xac, 0x22, 0x14, 0x03, 0x2e, 0xd0, 0xa8, 0xee, 0x6f, 0xf4, 0x37, 0xfa, 0x27, 0xfd, 0xa9, 0x6a,
	0x97, 0x05, 0xdb, 0x71, 0x12, 0xa4, 0xf6, 0x8d, 0x73, 0xe6, 0xcc, 0xd1, 0x9c, 0xd9, 0x01, 0xce,
	0x26, 0xdf, 0x17, 0x79, 0xb8, 0x5c, 0xf8, 0x2b, 0x9a, 0x1a, 0x7e, 0x44, 0xfb, 0xcb, 0x34, 0xc9,
	0x13, 0x7c, 0x32, 0x4f, 0xa2, 0x3e, 0xfd, 0xe1, 0x47, 0xcb, 0x85, 0xa0, 0xd4, 0x5f, 0x12, 0xe0,
	0x0d, 0xf1, 0x84, 0x66, 0x99, 0x7f, 0x47, 0xb1, 0x0f, 0xbd, 0x68, 0x87, 0x75, 0x57, 0x4b, 0xaa,
	0x48, 0x17, 0xd2, 0x65, 0xe7, 0xf3, 0x55, 0x7f, 0xc7, 0xaa, 0x3f, 0x79, 0xb2, 0xc1, 0x7e, 0xc6,
	0x08, 0x9f, 0xc3, 0x51, 0x44, 0x33, 0x8e, 0x95, 0xbd, 0x0b, 0xe9, 0xb2, 0x65, 0x57, 0x58, 0xfd,
	0x2d, 0x01, 0xd8, 0x49, 0x12, 0x0d, 0x52, 0xea, 0xe7, 0x14, 0xbf, 0x07, 0x39, 0x4d, 0x92, 0xc8,
	0x4d, 0xee, 0x69, 0xcc, 0x07, 0x90, 0xed, 0x35, 0xc1, 0x8c, 0x18, 0x98, 0xfa, 0x51, 0x61, 0x24,
	0xdb, 0x15, 0x2e, 0x6b, 0x4e, 0xf8, 0x93, 0x2a, 0x8d, 0x75, 0x8d, 0x61, 0xac, 0xc0, 0x21, 0x37,
	0x71, 0x2d, 0x65, 0x9f, 0x97, 0x4a, 0x88, 0x7b, 0xd0, 0x64, 0x9f, 0x66, 0xa0, 0x1c, 0xf0, 0x82,
	0x40, 0x8c, 0xbf, 0xf3, 0x23, 0x6a, 0x06, 0x4a, 0xb3, 0xe0, 0x0b, 0xa4, 0x5e, 0xc2, 0x11, 0x9b,
	0x76, 0x94, 0x84, 0xf1, 0xcb, 0xb3, 0xaa, 0x57, 0x20, 0x33, 0xa5, 0x45, 0xfd, 0x87, 0x9a, 0x58,
	0xea, 0x47, 0x38, 0x66, 0x52, 0x9d, 0x66, 0x79, 0x9a, 0xac, 0x6a, 0xc4, 0x62, 0x82, 0xa1, 0xbf,
	0xc8, 0x6b, 0x94, 0x43, 0xe8, 0x30, 0xa5, 0x41, 0x73, 0x9d, 0xe6, 0x7e, 0xb8, 0xc8, 0x6a, 0xb6,
	0xab, 0xc0, 0x61, 0xf1, 0x76, 0x99, 0xb2, 0x77, 0xd1, 0x60, 0x5b, 0x12, 0x50, 0x35, 0xa1, 0xcd,
	0x9c, 0xb4, 0x20, 0xb8, 0xe6, 0x4c, 0xfd, 0x33, 0x15, 0x9d, 0x66, 0x50, 0x3e, 0x53, 0x89, 0xd5,
	0x51, 0x31, 0xd4, 0x38, 0x9c, 0xdf, 0xff, 0xb7, 0x97, 0x09, 0x5d, 0xe6, 0xe5, 0xd0, 0x38, 0x28,
	0xaf, 0xb9, 0x36, 0x61, 0x44, 0xd7, 0x77, 0x28, 0xdb, 0x25, 0x54, 0x3f, 0x55, 0xbb, 0x2a, 0xa6,
	0xca, 0xb6, 0x6e, 0x4d, 0xda, 0xbe, 0x35, 0x95, 0x40, 0x5b, 0xc8, 0xcc, 0x98, 0xb5, 0x6d, 0xae,
	0x4e, 0xda, 0x5a, 0xdd, 0x4b, 0x27, 0xab, 0x7e, 0x83, 0x96, 0x41, 0x63, 0x9a, 0x86, 0x73, 0xf2,
	0x40, 0xe3, 0x1c, 0x1b, 0x20, 0x53, 0xf6, 0xf1, 0x6f, 0x7f, 0xdf, 0xba, 0xf7, 0xf9, 0x9c, 0x1f,
	0xfe, 0x34, 0xa0, 0xf7, 0x74, 0x3f, 0xee, 0xc2, 0xb1, 0x3d, 0x9b, 0x4d, 0xbc, 0x81, 0x4d, 0x34,
	0x97, 0xa0, 0x57, 0xb8, 0x0d, 0x32, 0x27, 0x46, 0x33, 0x73, 0x8a, 0x24, 0xdc, 0x01, 0xe0, 0xd0,
	0x22, 0xda, 0x0d, 0x41, 0x7b, 0x18, 0x41, 0x8b, 0x63, 0x9d, 0x38, 0xae, 0x3d, 0xbb, 0x45, 0x8d,
	0xaa, 0x61, 0xa8, 0x59, 0x2e, 0xda, 0xc7, 0xaf, 0x01, 0x71, 0x68, 0x10, 0xd7, 0xd3, 0x89, 0xab,
	0x99, 0x96, 0x83, 0x0e, 0xf0, 0x29, 0x74, 0x39, 0xab, 0xe9, 0xba, 0x77, 0x6d, 0x69, 0xb7, 0xc4,
	0x46, 0xcd, 0x4a, 0x3a, 0x36, 0x07, 0xe3, 0x92, 0x3d, 0xc4, 0x67, 0x70, 0xc2, 0x59, 0x87, 0x4c,
	0x75, 0x6f, 0x42, 0x1c, 0x47, 0x33, 0x08, 0x3a, 0xda, 0xf2, 0x2d, 0xb4, 0x0e, 0x92, 0x99, 0xaf,
	0x00, 0x9e, 0x39, 0xf5, 0x98, 0x00, 0x41, 0xe5, 0x50, 0x64, 0xf2, 0xc8, 0x0d, 0x99, 0xba, 0xe8,
	0xb8, 0x9a, 0x81, 0x25, 0x13, 0x64, 0xab, 0xb2, 0xe5, 0xf9, 0x04, 0xdb, 0xc6, 0x3d, 0xc0, 0x9b,
	0x29, 0x05, 0xdf, 0xa9, 0x2c, 0x58, 0x56, 0x41, 0x76, 0xf1, 0x39, 0xf4, 0x1e, 0x27, 0x16, 0x35,
	0x84, 0xdf, 0xc2, 0xd9, 0xa3, 0xdc, 0xa2, 0x74, 0x52, 0xb5, 0x6d, 0xa4, 0x17, 0x35, 0x8c, 0xdf,
	0xc1, 0x9b, 0x9d, 0x1d, 0x88, 0xe2, 0xe9, 0xd7, 0x26, 0x3f, 0x88, 0x2f, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x60, 0x15, 0x5c, 0x89, 0x05, 0x06, 0x00, 0x00,
}
